### ISSUE TITLE
Improve Route 53 support

### ISSUE THREAD

**Issue by danieldreier** [puppetlabs/puppetlabs-aws#100]
As far as I can tell, the Route 53 providers only cover A, NS, and TXT records. At a minimum, to manage the existing puppetlabs.com DNS using this, we'd also need:

- AAAA
- CNAME
- MX
- SPF

Beyond that, the ability to set Route 53 routing policies based on their simple, weighted, latency, failover, and geo-location options is important. We're not currently using any of those, but intend to fairly soon.

In particular, the ability to associate a DNS entry with a health check is significant, because for some services we're planning on running our own load balancers and would like to use DNS failover as part of that. I believe this would also require adding management of health checks to this module.

**Comment by garethr** [comment]
@danieldreier thanks. We should be able to add the other DNS types quickly as that's mainly boilerplate.

We're definitely interested in adding routing options and health checks too, although that might take a little longer. If you have chance, an example manifest of how you imagine the health check type working would be particularly useful.

**Comment by garethr** [comment]
This has been merged into master. Thanks for the suggestion.
