### ISSUE TITLE
multiple versions of json_pure gem installed cause issues

### ISSUE THREAD

**Issue by pjfoley** [puppetlabs/puppetlabs-aws#101]
Hi,

Not sure if there is anything we can do, however thought I would flag it.

I had both json_pure-1.8.1 and json_pure-1.8.2 installed.

When running:
puppet apply tests/create.pp --noop

I would get a 
#<MultiJson::AdapterError: Did not recognize your adapter specification (can't activate json_pure-1.8.1, already activated json_pure-1.8.2).>

To fix I had to uninstall json_pure-1.8.1

**Comment by garethr** [comment]
I wasn't able to recreate this and I've not heard the issue arrise from other users. Certainly odd. I'll close, but keep a look out if I see it elsewhere. The move to puppet-agent should make this sort of conflict much less likely all being well.
