### ISSUE TITLE
security_group_ids not supported for ec2_instance

### ISSUE THREAD

**Issue by msingh4** [puppetlabs/puppetlabs-aws#105]
When creating instances in non-default VPC, AWS requires subnet and security_group_ids parameter.  The security_group parameter does not work with subnet. It seems ec2_instance does not support security_group_ids  and I get the following error 

`````
Debug: Ec2_instance[msapp-1]: Adding default for region
Debug: Ec2_instance[msapp-1]: Adding default for availability_zone
Error: Invalid parameter security_group_ids at /media/sf_e31496/puppet_local/modules/puppetlabs-aws/msingh-tests/ms1.pp:74 on node ubuntu.home.internal
Error: Invalid parameter security_group_ids at /media/sf_e31496/puppet_local/modules/puppetlabs-aws/msingh-tests/ms1.pp:74 on node ubuntu.home.internal

`````

Thanks -
Manjeet

**Comment by garethr** [comment]
Hi @msingh4. Could you post your Puppet manifest as well please? I'll take a look.

**Comment by msingh4** [comment]
Ok.  I have tried with security group names and Ids. Replaced some chars with * for some anonymity. 

Anything thats not a comment , here . 
$ grep -v "^#"  modules/puppetlabs-aws/msingh-tests/ms1.pp 

Ec2_securitygroup {
  region => 'us-west-2',
}

Ec2_instance {
  region            => 'us-west-2',
  availability_zone => 'us-west-2b',
}






ec2_instance { 'msapp-1':
  ensure          => present,
  image_id        => 'ami-0b5f073b',
  #security_groups => ['sg-128cd***'],
  security_group_ids => ['sg-128cd***'],
  instance_type   => 't2.micro',
  subnet   => 'subnet-3******',
  key_name   => 'msingh-*****',
  tags            => {
    department => 'engineering',
    project    => 'cloud',
    created_by => $::id,
  },
}

**Comment by garethr** [comment]
@msingh4 thanks for posting the manifest. The modules uses the names rather than the AWS ID for referring to resources. So you probably want something similar to this:

```puppet
ec2_instance { 'msapp-1':
  ensure          => present,
  image_id        => 'ami-0b5f073b',
  security_groups => ['your-security-group-name'],
  instance_type   => 't2.micro',
  subnet          => 'your-subnet-name',
  key_name        => 'msingh-**',
  tags            => {
    department => 'engineering',
    project    => 'cloud',
    created_by => $::id,
  },
}

**Comment by msingh4** [comment]
Thanks Gareth,  I think I tried both name and id option for subnet and security_groups but I will test them again to see if I run into any issue. 
Appreciate your help !
-Manjeet

**Comment by msingh4** [comment]
It worked. I had subnet without name tag. Added name and then it worked.  Thanks
