### ISSUE TITLE
enable public IP on ec2 nodes

### ISSUE THREAD

**Issue by danieldreier** [puppetlabs/puppetlabs-aws#106]
In the AWS web interface, it's possible to have AWS auto-assign a public IP to an ec2 node upon creation. However, the public_ip_address parameter on ec2_instance seems to be read-only. 

I'm working around that by enabling public IP assignment by default for our subnets, but it'd be great to have a per-node override, because without a NAT node there's no internet access unless you assign a public IP.

**Comment by garethr** [comment]
This appears to be a case of passing `associate_public_ip_address: true` to the run_instances method. Will look into soon.

**Comment by garethr** [comment]
Note that this is available in https://github.com/puppetlabs/puppetlabs-aws/pull/114

**Comment by garethr** [comment]
The code from #114 was merged and this is now supported. Closing.
