### ISSUE TITLE
add support for private route 53 zones

### ISSUE THREAD

**Issue by danieldreier** [puppetlabs/puppetlabs-aws#109]
I'd like to create a private route 53 DNS zone in our VPC. As a transitional measure until we figure out what to do with our DNS altogether, I'm planning on delegating a subdomain to route 53 and registering AWS EC2 instances under that, just for internal addressing. It doesn't look like it's possible to configure private zones inside of a VPC using the current route53_zone type and provider.

**Comment by danieldreier** [comment]
I no longer need this -- it turns out that private VPC DNS zones aren't reachable from outside of the VPC even when using a VPN, so there's little utility to us; we can't delegate a subdomain there. Somebody else may still need this, but I don't.

**Comment by zabacad** [comment]
#418 should cover this.
