### ISSUE TITLE
Manage EBS volumes

### ISSUE THREAD

**Issue by danieldreier** [puppetlabs/puppetlabs-aws#112]
As far as I can tell, there isn't an existing way to provision EBS volumes independently of creating VMs. I'll need to do that for our web stack, because we need to use an NFS server, and the way I'd like to do HA failover for it on AWS will be to create an EBS volume that gets automatically attached to a secondary NFS server which also takes over the floating IP. That would allow me to skip using lsyncd or similar to keep the two nodes in sync. It would be critical to be able to specify that the volume not be destroyed when the node it's attached to is destroyed.

**Comment by evidex** [comment]
:+1: Would love to see this supported.

**Comment by zleswomp** [comment]
+1

**Comment by mikronac** [comment]
+1

**Comment by zleswomp** [comment]
See https://github.com/puppetlabs/puppetlabs-aws/pull/281

**Comment by beergeek** [comment]
+1

**Comment by brianeclow** [comment]
When will a new version be stamped? This will include the much wanted enhancements included in #400 ( aka #281 )?

**Comment by ahenroid** [comment]
I believe this issue has been addressed by https://github.com/puppetlabs/puppetlabs-aws/pull/400, and if so, I'm planning to close this. If I'm wrong, please speak up. Thank you!
