### ISSUE TITLE
ec2_securitygroup vpc parameter invalid

### ISSUE THREAD

**Issue by s4mur4i** [puppetlabs/puppetlabs-aws#133]
Hy,

I am trying to add a vpc parameter to ec2_securitygroup and get following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter vpc on Ec2_securitygroup[test-sg] at /etc/puppet/modules/profile/manifests/puppetmaster_tasks.pp:23 on node puppet.3amlabs.net

The declarations is following:

ec2_securitygroup { 'test-sg':
    ensure      => present,
    region      => 'us-east-1',
    vpc         => 'x-test',
    description => 'Security group for VPC',
    ingress     => [{
      security_group => 'test-sg',
    },{
      protocol => 'tcp',
      port     => 22,
      cidr     => '0.0.0.0/0'
    }]
  }

It's a basic one taken from https://github.com/puppetlabs/puppetlabs-aws/blob/master/examples/vpc-example/init.pp#L10

Has VPC option been removed?
The vpc is a valid one: 
 puppet resource ec2_vpc | grep test
ec2_vpc { 'x-test':

thanks
Krisztian

**Comment by garethr** [comment]
Hi @s4mur4i. Could I check how you installed the module? The version from the Forge (installed with puppet module tool) currently doesn't have the VPC security group support, although it's available in master from GitHub. We'll be releasing a new version soon so I'll update here when we do so. If that's not the problem let me know and I'll help debug.

**Comment by daveseff** [comment]
Actually I was testing this directly from github master and was getting this:

Notice: /Stage[main]/Main/Ec2_securitygroup[sample-sg]: Dependency Ec2_vpc[sample-vpc] has failures: true
Warning: /Stage[main]/Main/Ec2_securitygroup[sample-sg]: Skipping because of failed dependencies
Error: Could not find a suitable provider for ec2_vpc
Error: Could not find a suitable provider for ec2_vpc_internet_gateway
Error: Could not find a suitable provider for ec2_vpc_routetable
Error: Could not find a suitable provider for ec2_vpc_subnet
Notice: Finished catalog run in 13.88 seconds

This is directly from the examples with the exception that I'm doing us-west-1

**Comment by s4mur4i** [comment]
Hy @garethr . 

Okay got it working from cloneing the github version. 
On a side note: the runtime for one sg creation is a little high, but I will investigate it further:
Notice: Finished catalog run in 108.97 seconds
Thanks for the info.

**Comment by garethr** [comment]
@s4mur4i thanks. I'll close this issue. We'll be releasing a new version to the Forge soon.

Regarding performance, particular for security groups, it's a factor of the number of security groups you have in all regions at the moment.

We're currently testing the following PR https://github.com/puppetlabs/puppetlabs-aws/pull/102 which I've seen reduce this by 80% in similar runs. And we'll be looking to more performance improvements at a later date.

You can also cut this down by if you're only managing resources in a single region by using the `AWS_REGION` environment variable.

**Comment by garethr** [comment]
@daveseff I'm guessing you might have an older version of the module installed on the module path. You can override that with the `--modulepath` like so:

    puppet apply tests/create.pp --modulepath ../ --test

If that's not that case please do open an new issue with the steps to try and recreate it. Thanks.

**Comment by daveseff** [comment]
@garethr I'm using Puppet Enterprise and there's only one module installed. 

Using This still fails with same errors:

puppet apply vpc_test.pp --modulepath /etc/puppetlabs/puppet/environments/production/modules --test

**Comment by daveseff** [comment]
@garethr This was my fault. I didn't have the retries gem installed. this must have been a new requirement?
