### ISSUE TITLE
ec2_securitygroup does not support port ranges

### ISSUE THREAD

**Issue by danieldreier** [puppetlabs/puppetlabs-aws#141]
Using the AWS console, I altered a security group to include a custom TCP group with a custom port range (49152 - 49160). It registered in the console, but when I used `puppet resource ec2_securitygroup` to view the puppet representation it only showed port 49160: (example is redacted, relevant parts are still there).

```puppet
ec2_securitygroup { 'glusterfs':
  ensure      => 'present',
  description => 'allow glusterfs ports',
  ingress     => [
    {'cidr' => '192.168.0.0/16', 'port' => '49160', 'protocol' => 'tcp'},
  ],
  region      => 'us-west-2',
  vpc         => 'production',
}
```

Not only that, but if I run my normal puppet apply that manages that security group, it fails with `failed: The specified rule does not exist in this security group.` When I manually delete the port range entry in the AWS console puppet runs fine again.

I can work around this by iterating over a list and creating individual rules for each port, but it's a little awkward.

**Comment by garethr** [comment]
Odd. I've just tried the following test case and not been able to trigger this:

(I've tested this with master, which code wise should be identical to 1.0.0 from the Forge. Could you check what version of the module you're running? The ability to manage port ranges was added quite close to 1.0 shipping).

With the following Puppet code:

```
ec2_securitygroup { 'lb-sg':
  ensure      => present,
 region => 'sa-east-1',
  description => 'Security group for load balancer',
  ingress     => [{
    protocol  => 'tcp',
    from_port => 80,
    to_port   => 88,
    cidr      => '0.0.0.0/0'
  }],
}
```

I can run without issue:

```
$ puppet apply tests/sg.pp --test
Info: Loading facts
Notice: Compiled catalog for pro.local in environment production in 0.06 seconds
Info: Applying configuration version '1427971394'
Info: Checking if security group lb-sg exists in region sa-east-1
Info: Creating security group lb-sg in region sa-east-1
Notice: /Stage[main]/Main/Ec2_securitygroup[lb-sg]/ensure: created
Notice: Finished catalog run in 3.18 seconds
$ puppet apply tests/sg.pp --test
Info: Loading facts
Notice: Compiled catalog for pro.local in environment production in 0.06 seconds
Info: Applying configuration version '1427971413'
Info: Checking if security group lb-sg exists in region sa-east-1
Notice: Finished catalog run in 2.35 seconds
```

And retrieve the port range via puppet resource:

```
puppet resource ec2_securitygroup lb-sg
ec2_securitygroup { 'lb-sg':
  ensure      => 'present',
  description => 'Security group for load balancer',
  ingress     => [{'cidr' => '0.0.0.0/0', 'from_port' => '80', 'protocol' => 'tcp', 'to_port' => '88'}],
  region      => 'sa-east-1',
}
```

Could you try this test case out and report back?

The relevant acceptance tests are https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/acceptance/securitygroup_spec.rb#L426-L477.

**Comment by garethr** [comment]
@danieldreier if this is still an issue let me know and I'll reopen. But I think this should now work as expected/documented.
