### ISSUE TITLE
EC2 instance roles

### ISSUE THREAD

**Issue by MarsuperMammal** [puppetlabs/puppetlabs-aws#148]
Unless I'm blind, it appears that the ec2 instance configurations don't allow for specifying an IAM_role for the instance being launched. This seems like a pretty useful feature. Leaving the note here, to hopefully be pointed to how I can't ready, but otherwise, I'll be working on a PR shortly.

**Comment by pjfoley** [comment]
Hi @MarsuperMammal 

It looks like my PR (https://github.com/puppetlabs/puppetlabs-aws/pull/59) to add this was just merged into master.

**Comment by garethr** [comment]
@MarsuperMammal you're correct, and thanks to @pjfoley for adding that feature.
