### ISSUE TITLE
Referencing ephemeral instance storage in block_devices mapping

### ISSUE THREAD

**Issue by ginkel** [puppetlabs/puppetlabs-aws#152]
Is there a way to reference ephemeral instance storage for the block_devices mapping of an ec2_instance? Reading the source I'm under the impression that only EBS may be supported...

**Comment by benpillet** [comment]
I'm running into the same issue.  I tried specifying the virtual_name as ephemeral0, but still no luck.  Terraform splits out the root_block_device, ebs_block_device, and ephemeral_block_device into separate attributes as noted here: https://www.terraform.io/docs/providers/aws/r/instance.html.  I could see the implementation going either way.  To keep backwards compatibility, we could add another field to the array entry for a block_device with a name like storage_type and values like ['ebs', 'instance'] with ebs being the default.  Or split out the different storage types like terraform.  I was thinking of working on this in the next few days.  Any preference on the implementation?

**Comment by ahenroid** [comment]
@ginkel @benpillet, I believe this addressed by #212. Can I close this issue?

**Comment by benpillet** [comment]
Yes.  Looks like #212 covers it.  Thanks!

**Comment by ahenroid** [comment]
Thanks, @benpillet!
