### ISSUE TITLE
All your feature are belong to us

### ISSUE THREAD

**Issue by jhoblitt** [puppetlabs/puppetlabs-aws#153]
I am investigating solutions for retrying IPC/RPC operations in a module I'm working on and suspect that the pattern in which this module uses the retries gem is a good archetype.  However, I'm concerned that it's "asking for trouble" to have more than one module defining the same feature.  I've thought of a couple of possible solutions, and acknowledge that an issue attached to this module isn't an ideal forum, but hope that starting a discuss here will reach the relevant audience.

Options I've considered:
1. Essentially, do nothing and gamble that if multiple modules in the same environment redundantly define the same feature, nothing bad happens.
2. Namespace features in some way to avoid collisions.  Ie, `:retires` becomes `:aws_retires` or pedantically `:puppetx_aws_retires`.
3. Add new confine functionality such that a feature is no longer needed to place a dependency on a gem.  Something along the lines of `Puppet::Confine::Lib` or `Puppet::Confine::Gem`.
4. Factor the `:retries` feature out into it's own module, perhaps with a DSL class to handle installation of the gem.

Of these, I suspect \3 is most robust solution.  However, I'm not familiar with the confine[r] and would need to do some experimentation.  From a very quick inspection of the code, I suspect if a module supplied a class under the `Puppet::Confine::` name space it would get picked up by `Puppet::Confine#test` via `require "puppet/confine/#{name}`.  If implementing this would require a change to be merged into core, it's still probably worth doing, but would have a longer lead time than is acceptable for my immediate needs.

I expect \4 to be a fast and cheap solution but would require the cooperation of this module.

There probably should be some sort of guidelines established along the lines of \2, if the usage of features grows in popularity, but I don't feel its a good solution to duplicate features.

I'm sure there are other possible solutions that I have missed.  Do any of the maintainers of this module have thoughts/opinions about this?

**Comment by ahenroid** [comment]
@jhoblitt, I'm doing some house cleaning, and this issue is rather old now and hasn't had any activity. Can I close this? Thanks!

**Comment by jhoblitt** [comment]
sure

**Comment by jhoblitt** [comment]
FYI - https://github.com/jhoblitt/puppet-confinelibs
