### ISSUE TITLE
ec2_elastic_ip fails in autoscaling (same name)

### ISSUE THREAD

**Issue by CarmenAPuccio** [puppetlabs/puppetlabs-aws#160]
https://github.com/puppetlabs/puppetlabs-aws/blob/master/examples/elastic-ip-addresses/README.md
ec2_elastic_ip needs to support instance_id as the same name can be used multiple times which leads to failure. Also, in an autoscale scenario it doesn't attach to the new node because the terminated node still carries the name you are trying to attach to. If it was instance_id you could use factor facts for ec2_instance_id in your manifests. Please help and support instance_id as well. Error below.

Warning: Multiple instances found named ePixFTPQAv1.0, using i-6cbf8743
Error: Could not set 'attached' on ensure: stopped waiting, encountered a failure state at 21:/opt/releases/puppet/manifests/site.pp
Error: Could not set 'attached' on ensure: stopped waiting, encountered a failure state at 21:/opt/releases/puppet/manifests/site.pp
Wrapped exception:
stopped waiting, encountered a failure state
Error: /Stage[main]/Main/Ec2_elastic_ip[52.7.57.238]/ensure: change from detached to attached failed: Could not set 'attached' on ensure: stopped waiting, encountered a failure state at 21:/opt/releases/puppet/manifests/site.pp

ec2_elastic_ip { '52.7.57.238':
  ensure   => 'attached',
  instance => 'ePixFTPQAv1.0',
  region   => 'us-east-1',
}

**Comment by ahenroid** [comment]
@CarmenAPuccio, reading through the thread, I believe this was resolved for you by #188. Can I close this issue? Thanks!
