### ISSUE TITLE
ec2_vpc_subnet - auto assign public ip

### ISSUE THREAD

**Issue by tintheparkin** [puppetlabs/puppetlabs-aws#162]
Hi there!

Great work on this module, I have been using it to see if we can speed up our deployment processes. One thing I would like to know is if it's possible to set "Auto Assign Public IP" to true while building ec2_vpc_subnet subnets?

**Comment by garethr** [comment]
Hi @tintheparkin. It is indeed (although I've just noticed this isn't documented in the README. You can set `map_public_ip_on_launch` to true on the subnet: https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/type/ec2_vpc_subnet.rb#L56

**Comment by tintheparkin** [comment]
Hi garethr. Thanks for the quick response, that has helped me greatly! I still have a issue regarding the assigning of public DNS though. A public IP is mapped just fine, but the public dns address is not assigned at all. I am wondering about the "public_dns_name" parameter, can this be set to assign a public dns address on an ec2 instance? I ask because we use the public dns a lot for monitoring (where IP is not fully functional for my needs) and for accessing metadata info.

Thanks again for your help!
