### ISSUE TITLE
Using images to explain examples

### ISSUE THREAD

**Issue by pjfoley** [puppetlabs/puppetlabs-aws#170]
Hi,

I was wondering if any thought had been given to allowing contributors to use pictures to explain particular architectures in the examples folder?

Looking at this stackexchange article - [how to add a screenshot to readmes in github] (http://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository)

To not pollute the master branch a suggestion is to create a separate screenshots (or images) branch which only contains the pictures.

Would this be something you would allow?

**Comment by garethr** [comment]
Absolutely, in fact one of the recent PR's added images to one of the examples.

https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/postgres-rds-example

With regards having a separate branch for those images that's not a bad idea. I'll have a chat with the wider modules team at Puppet Labs about that so we're doing the same for different modules. @mhaskel  @hunner @DavidS

**Comment by DavidS** [comment]
For a couple of small files like this, I see no problem.
