### ISSUE TITLE
Error: Could not autoload puppet/type/ec2_securitygroup: /etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:9: syntax error, unexpected ':', expecting ')'

### ISSUE THREAD

**Issue by Dharmender-Singh** [puppetlabs/puppetlabs-aws#184]
Does anyone have experience with getting the puppetlabs-aws module to work? I am running:

Puppet 3.8.1
Centos 6.5
Ruby 1.9.3p484
Following the "https://forge.puppetlabs.com/puppetlabs/aws "on the forge.

I should be able to run commands like

puppet apply tests/create.pp --test

But I keep getting the error:

[root@puppetmaster tests]# puppet apply create.pp
Error: Could not autoload puppet/type/ec2_securitygroup: /etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:9: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:74: syntax error, unexpected kEND, expecting $end
Error: Could not autoload puppet/type/ec2_securitygroup: /etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:9: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:74: syntax error, unexpected kEND, expecting $end on node puppetmaster.rbidev.ds
Error: Could not autoload puppet/type/ec2_securitygroup: /etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:9: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/etc/puppet/environments/production/modules/aws/lib/puppet/type/ec2_securitygroup.rb:74: syntax error, unexpected kEND, expecting $end on node puppetmaster.rbidev.ds
[root@puppetmaster tests]#
![error](https://cloud.githubusercontent.com/assets/12389415/8206441/096379d4-1517-11e5-91a7-fad5b4b7e93c.JPG)

What am I missing??

**Comment by garethr** [comment]
This looks like puppet is running under Ruby 1.8 from the error.

How was puppet installed?

**Comment by Dharmender4956** [comment]
sudo rpm -ivh http://yum.puppetlabs.com/el/6.4/products/x86_64/puppetlabs-release-6-11.noarch.rpm

sudo yum install -y puppet-server

**Comment by Dharmender4956** [comment]
Firstly I have installed the ruby 1.9.3 using link :https://digitalchild.info/centos-6-5-and-ruby1-9-3-via-software-collections/

then installed the puppet using these two commands : 

sudo rpm -ivh http://yum.puppetlabs.com/el/6.4/products/x86_64/puppetlabs-release-6-11.noarch.rpm

sudo yum install -y puppet-server

**Comment by jasgag01** [comment]
I'm having the same issue.  Any luck @Dharmender4956

**Comment by garethr** [comment]
I think the best approach here is (if possible) for you to try out the new Puppet All-in-One installer https://puppetlabs.com/blog/welcome-puppet-collections. These new packages include a modern version of Ruby specifically for use by Puppet.

**Comment by jasgag01** [comment]
Thanks @garethr I installed pc1 and installed module using both the forge and cloning from git.  Also, I am running all this from an AWS RHEL 6.6 instance.  Unfortunately, now I get a new error when trying to run the included 'create.pp' file:

Error: Could not find a suitable provider for ec2_securitygroup
Error: Could not find a suitable provider for ec2_instance
Error: Could not find a suitable provider for elb_loadbalancer

Thanks,

Jason

**Comment by garethr** [comment]
HI @jasgag01, my guess is your missing the relevant libraries, in particular the AWS SDK.

Try using /opt/puppetlabs/puppet/bin/gem to install the gems, so:

`/opt/puppetlabs/puppet/bin/gem install aws-sdk-core retries`

If that works I'll update the documentation. Thanks for trying this out.

**Comment by jasgag01** [comment]
That did the trick.  I didn't use the full path to "gem" when I installed the packages.  It would be useful to have within the documentation.

@garethr Thanks for your help!

**Comment by seyedk** [comment]
I have followed all the documentations, Initially I was getting Could not find a suitable provider for ec2_securitygroup, but after applying `/opt/puppetlabs/puppet/bin/gem install aws-sdk-core retries` I'm getting the following error:
`Error: Failed to apply catalog: uninitialized constant Aws::EC2`
