### ISSUE TITLE
ec2_vpc_routetable: Instances as Gateways

### ISSUE THREAD

**Issue by lynxdigital** [puppetlabs/puppetlabs-aws#196]
After conducting a whole bunch of experimentation with the ec2_vpc_routeable function it appears that Instances (configured as NATs) can't be added as gateways. Is this assumption correct? I had a quick look at the function code and saw nothing referencing instance-id during the route creation.

When trying to add an Instance as a gateway - the route table is created with the local route only (no default gateway added as defined pointing to the NAT instance). Subsequent runs produce an error as the puppet module code does match what was created.

Adding the default gateway manually so it matches what is configured also produces an error.

>  Error: routes property is read-only once ec2_vpc_routetable created.
> Error: /Stage[main]/Infrastructure::Aim::Vpc::Routes/Ec2_vpc_routetable[Automation-Internal]/routes: change from [{"destination_cidr_block"=>"172.16.0.0/16", "gateway"=>"local"}] to {"destination_cidr_block"=>"172.16.0.0/16", "gateway"=>"local"} {"destination_cidr_block"=>"0.0.0.0/0", "gateway"=>"Automation-Gateway"} failed: routes property is read-only once ec2_vpc_routetable created.

As you can see, the added instance-id in the first part of the error is not even mentioned.

Has anybody found a way to add instances as gateways via Puppet? I really don't want to have to call upon exec/aws cli to replace the routetable function if I can help it.

Thanks.

**Comment by lynxdigital** [comment]
It's OK. I figured it out!

I've made changes to the AWS Puppetlabs module which extends the route table creation function and allows EC2 instances to become gateways in the route table configuration. We are now able to create our own custom NATs for outgoing traffic and traffic between subnets.

Thanks again.

**Comment by garethr** [comment]
Hi @lynxdigital. I'll keep this open as it sounds like something the module might be able to handle in the future. If you'd be up for submitting a pull request, or posting your modifications, then that would be great.

**Comment by lynxdigital** [comment]
Unfortunately I'm not sure how to set-up a pull request within github - I primarily use a local ssh/git setup and not github (not my choice). If you can point me to a good document/tutorial on how to go about setting up a pull request I'd be more then happy to post the code changes I made.

**Comment by garethr** [comment]
@lynxdigital no problem. The GitHub documentation is pretty good http://help.github.com/send-pull-requests/. But if that provides a problem feel free to just create a diff from git and upload here.

**Comment by earsdown** [comment]
+1

**Comment by rfletcher** [comment]
> I've made changes to the AWS Puppetlabs module which extends the route table creation function and allows EC2 instances to become gateways

@lynxdigital Have you published your patch anywhere? I have the same issue it'd be great to use your fix.

**Comment by olliiiver** [comment]
+1

**Comment by ahenroid** [comment]
@lynxdigital, it sounds like you found a work-around for this. Can I close this issue? We can reopen if this comes again for anyone. Thanks!
