### ISSUE TITLE
Can this be used with puppet masterless and what would be best practices...

### ISSUE THREAD

**Issue by dfuentes77** [puppetlabs/puppetlabs-aws#204]
I'd love to use this gem along with Hiera, r10k, but could i use them with puppet masterless.

Any help or links would be great.

Thanks!

**Comment by garethr** [comment]
You can absolutely use this module in a masterless model. In fact most of the [examples](https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples) take that route to make it easy to get started. And [one of the examples even uses Hiera](https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/hiera-example).

With regards r10k, you could use r10k's dependency management features to manage a list of modules (like this one) in a masterless model, though many of the other features of r10k are about interacting with a master.

You might find [Pupa](https://github.com/daenney/pupa interesting too from @daenney.

**Comment by dfuentes77** [comment]
A few more questions:

Does this module also manage the signing of the certs for puppet or is that even necessary in a masterless setup?  And if not, since this module supports setting up autoscaling groups, how is masterless puppet suppose to get onto a newly created node in an ASG?

What is the ENC in this kind of setup? Is that hiera but as commited code in the puppet repo?

Are there any good examples of using theforeman in this kind of masterless setup that you guys (puppetlabs) recommend?

Thanks!

**Comment by garethr** [comment]
Hi @dfuentes77. You would be better to ask more general questions like these in the puppet-user mailing list. The AWS module is at a lowevr level that the questions you're asking. 

With regards to installing Puppet onto nodes provisioned by the module, you can either create an AMI which already have Puppet installed and running, or you can use the userdata script to install and run Puppet on instance creation. You can see a basic example here: https://github.com/puppetlabs/puppetlabs-aws/blob/master/examples/puppet-enterprise/pe_agent.pp#L11

**Comment by dfuentes77** [comment]
Thanks you!
