### ISSUE TITLE
Outbound attribute for ec2_securitygroup

### ISSUE THREAD

**Issue by DoctahPopp871** [puppetlabs/puppetlabs-aws#207]
Currently can define ingress attributes, but can not define egress attributes for ec2_securitygroup resource. Is creating the egress type for this resource in the cards ?

egress            => [{
    protocol      => 'tcp',
    port             => 6000,
    cidr             => '0.0.0.0/0',

**Comment by earsdown** [comment]
+1

**Comment by daveseff** [comment]
I'm working on this as I am needing this feature. Look for a PR soon.

**Comment by daveseff** [comment]
@garethr :
#273 adds Egress (Outbound) rules for Security groups. Just as you would do an ingress rule, an example would be:

    ec2_securitygroup { 'davetest' :
      ensure      => present,
      description => 'Dave Testing',
      vpc => $vpc,
      ingress     => [
        {cidr => '10.0.0.0/8', from_port => '12345', protocol => 'tcp', to_port => '12345'},
      ],
      egress      => [
        {cidr => '10.0.0.0/8', from_port => '54321', protocol => 'tcp', to_port => '54321'},
      ],
    }

By default security groups with no outbound rules set get a default rule of allowing everything outbound. This is still the case with this patch if no egress rules are defined. Once egress rules are defined puppet will remove the default open rule.

**Comment by ahenroid** [comment]
@DoctahPopp871 @daveseff, I believe this was resolved by #273. Can I close this issue?
