### ISSUE TITLE
Allow rds_instance creation to accept a snapshot parameter

### ISSUE THREAD

**Issue by dfuentes77** [puppetlabs/puppetlabs-aws#209]
so that it can create an RDS instance restored from another db's snapshot like what "aws rds restore-db-instance-from-db-snapshot" would do via command-line tool

**Comment by ahenroid** [comment]
@dfuentes77 @daveseff, I believe this was resolved by #363. Can I close this issue?

**Comment by dfuentes77** [comment]
👍
