### ISSUE TITLE
IAM example is unusable

### ISSUE THREAD

**Issue by daveseff** [puppetlabs/puppetlabs-aws#224]
Trying to follow the IAM example in examples/iam-profile/README.md but the provided JSON is too large. AWS gives the following error:
`
An error occurred: Maximum policy size of 2048 bytes exceeded for user
`

**Comment by ngeorgieff** [comment]
I'm able to import the profile but ec2:* permissions are not enough to provision an instance.

**Comment by jsnod** [comment]
I am able to add it as a Managed Policy, but not as an Inline Custom Policy.

**Comment by zleswomp** [comment]
A PR to add IAM support has been opened: https://github.com/puppetlabs/puppetlabs-aws/pull/316

**Comment by ahenroid** [comment]
I believe this issue was addressed by #316. Can I close?

**Comment by zleswomp** [comment]
I think probably, but this might be something else in the README about how to setup puppet to have the correct permissions.  I glossed over a bit of that.
