### ISSUE TITLE
Can not add or remove instances from elb_loadbalancer once created. 

### ISSUE THREAD

**Issue by daveseff** [puppetlabs/puppetlabs-aws#225]
My class:
    class infra::clientelb {
        instances = ['host1', 'host2', ]
        $client_elbs = {
            'www-somedumbdomain-com' => { cert => 'somedumbcert.com', },
        }
    
    define clientELB($cert) {
          elb_loadbalancer { "${name}-elb" :
             ensure               => present,
             region               => 'us-east-1',
             instances            => $::infra::clientelb::instances,
             security_groups      => ['prod-lb'],
             subnets              => ['corp-pub',],
             scheme               => 'internet-facing',
             listeners            => [{
                protocol => 'HTTP',
                load_balancer_port => '80',
                instance_protocol => 'HTTP',
                instance_port  => '80',
                ssl_certificate_id => '',
             },{
                protocol => 'HTTPS',
                load_balancer_port => '443',
                instance_protocol => 'HTTP',
                instance_port  => '8080',
                ssl_certificate_id => "arn:aws:iam::(redacted):server-certificate/${cert}",
             },],
          }
       }
    
       create_resources(clientELB, $client_elbs)
     }

After the puppet agent runs, it creates the elb and adds the instances as ecpected. If I add 'host3' to my instances, I see this in puppet:
```
Notice: /Stage[main]/infra::Clientelb::Clientelb[www-somedumbdomain-com]/Elb_loadbalancer[www-somedumbdomain-com-elb]/instances: instances changed ['host1', 'host2'] to 'host1 host2 host3'
```

But I do not see the instance added to the elb in the AWS console. Also it seems to be converting a list to a string. Each puppet agent run give the same message, "instances changed ['host1', 'host2'] to 'host1 host2 host3'" so it's not actually changing anything.

**Comment by daveseff** [comment]
@garethr Any comment on this? This has become a blocker for my company's projects. We need to migrate a few hundred elbs and I wanted to use puppet to manage it all.

**Comment by vbarba** [comment]
Same happens to me. I try to modify instances in an ELB but doesn't happens.

**Comment by vbarba** [comment]
I have created a PR https://github.com/puppetlabs/puppetlabs-aws/pull/265/files for this. As is my first PR in github please be gentle :)

**Comment by vbarba** [comment]
merged :)
