### ISSUE TITLE
How to add the certificate to elb-loadbalancer

### ISSUE THREAD

**Issue by anishnath** [puppetlabs/puppetlabs-aws#229]
Getting the error while creating the Loadbalancer using hiera infrastructure 

Error: Could not set 'present' on ensure: Secure Listeners need to specify a SSLCertificateId
Error: Could not set 'present' on ensure: Secure Listeners need to specify a SSLCertificateId
Wrapped exception:
Secure Listeners need to specify a SSLCertificateId
Error: /Stage[main]/Main/Elb_loadbalancer[ph-att-prod-sllb]/ensure: change from absent to present failed: Could not set 'present' on ensure: Secure Listeners need to specify a SSLCertificateId

The documentation doesn't talk about the certificate Information how to use it  

elb_loadbalancer:
  my-lb:
    ensure            : present
    instances         : [ test-01 ]
    listeners         : [ { 'instance_port' : '80', 'instance_protocol' : 'HTTP', 'load_balancer_port' : '443', 'protocol' : 'HTTPS' } ]
    region            : us-west-2
    scheme            : internet-facing
    security_groups   : [ plb-secgrp ]
    subnets           : [west2b_subnet]

**Comment by bahrt** [comment]
Same error here, and probably same for cipher set. 
I tried a couple options like variations of ssl_certificate_id, or adding it to the template, but to no avail. 
Is it supported?

Cheers

**Comment by garethr** [comment]
I'm afraid at the moment this isn't supported, but a couple of folks have taken a run at PRs to add this functionality: https://github.com/puppetlabs/puppetlabs-aws/pull/219

**Comment by bahrt** [comment]
Yeah I saw it later on and actually got it working from #214.  I'll try #219 too as it looks more robust. Thanks.

**Comment by ahenroid** [comment]
@anishnath @bahrt, I believe this was addressed by #214. Can I close this issue?

**Comment by anishnath** [comment]
yes.. Thanks
