### ISSUE TITLE
aws feature not loaded in puppet >4.0.0

### ISSUE THREAD

**Issue by aequitas** [puppetlabs/puppetlabs-aws#230]
I am trying to get this module running in puppet  > 4.0.0 (currently 4.2.2) but i get the following errors:

    Error: Could not find a suitable provider for ec2_instance

Debugging shows this which might be related: 

    Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing

Running fine with 3.8.3

**Comment by brahman81** [comment]
Hi Aequitas, I encountered a similar issue to you whilst installing the module dependencies (aws-sdk-core,retries)

If running puppetserver the documentation states that installation of dependencies should be done using:

```
/opt/puppetlabs/bin/puppetserver gem install aws-sdk-core retries
```

But I found that using the below command was the only way that worked.

```
/opt/puppetlabs/puppet/bin/gem install aws-sdk-core retries
```

Hope that helps.

**Comment by garethr** [comment]
@brahman81 thanks for spotting that, I'll get the README updated.

**Comment by brahman81** [comment]
@garethr no worries at all.

For anyone else stumbling on this bug from a google/github search, I found out that the difference between the 2 commands is that "/opt/puppetlabs/bin/puppetserver gem install" is used for gems that the puppetserver requires to run puppet ruby code, on the other hand "/opt/puppetlabs/puppet/bin/gem install" is for individual modules that require ruby gems, ie in this case puppetlabs-aws.

**Comment by aequitas** [comment]
@brahman81 thx, I already resolved my issue, frankly by switching to Terraform (not because of this issue though). 
For context, I was not using Puppet server but just a `puppet apply` from a local repository where the gems where installed.
