### ISSUE TITLE
user_data aws puppet-labs heira configuration

### ISSUE THREAD

**Issue by anishnath** [puppetlabs/puppetlabs-aws#231]
I'm creating aws instnace using puppet-labs aws YAML imfrastructure example , the instance is created but #cloudconfig is not set,

vm-02:
    ensure: present
    region: us-west-2
    #availability_zone: us-west-2b
    subnet: w2c-subnet
    image_id: ami-5189a661
    instance_type: t2.micro
    key_name: west-trial
    user_data: " #cloud-config
                hostname: myhostname
                fqdn: myhostname.mydomainname"
    private_ip_address: 10.10.33.15
    security_groups: vm-02-secgrp

Is this is the right way to pass the user_data ?

**Comment by garethr** [comment]
Not quite, you need to use the multiline syntax for YAML. Looks like you got the answer on Ask: https://ask.puppetlabs.com/question/19624/user_data-aws-puppet-labs-heira-configuration/?sort=latest
