### ISSUE TITLE
Error:Could not autoload puppet/type/ec2_instance: /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:31:

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#233]
Does anyone have experience with getting the puppetlabs-aws module to work? 

I am running:

Puppet 3.8.3 

Centos 6.7

Ruby 1.8.7

Following the readme on the forge:

http://ift.tt/1Q4LHkQ

I should be able to run commands like

puppet apply tests/create.pp --test puppet apply tests/test.pp --test

But i keep getting the error:

*Error: Could not autoload puppet/type/ec2_instance: /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:31: syntax error, unexpected ':', expecting ')' newparam(:name, namevar: true) do ^ /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:227: syntax error, unexpected kEND, expecting $end Error: Could not autoload puppet/type/ec2_instance: /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:31: syntax error, unexpected ':', expecting ')' newparam(:name, namevar: true) do ^ /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:227: syntax error, unexpected kEND, expecting $end on node ******************** Error: Could not autoload puppet/type/ec2_instance: /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:31: syntax error, unexpected ':', expecting ')' newparam(:name, namevar: true) do ^ /etc/puppet/modules/aws/lib/puppet/type/ec2_instance.rb:227: syntax error, unexpected kEND, expecting $end on node ***************

In addition from the readme, I should be able to run commands like

puppet node_aws list. But i keep getting that the subcommand node_aws is unknown.

What am I missing?

Thanks,

Ram.

**Comment by garethr** [comment]
Hi @ram2valar. Unfortunately the module requires Ruby 1.9 or greater (https://forge.puppetlabs.com/puppetlabs/aws/readme#requirements) due to that being a dependency of the official Amazon SDK.

**Comment by ram2valar** [comment]
Hi,

Thanks for the update.

now i have updated ruby to 1.9 but getting error while installing puppet was module

**Comment by ram2valar** [comment]
puppet aws-module

**Comment by garethr** [comment]
I'd definitely recomment looking at the official installation instructions. The latest packages avoid the need for a system Ruby, and come with all of the dependencies in a single package: https://docs.puppetlabs.com/guides/install_puppet/install_el.html

**Comment by ram2valar** [comment]
Hi Gare, 

I followed the same link in your earlier post however once i installed the puppet labs repo, if i search for the latest puppet its been shipped with ruby of version 1.8.37.

Post that i upgraded ruby version to 1.9.3p551. using the following link:

http://tecadmin.net/install-ruby-1-9-3-or-multiple-ruby-verson-on-centos-6-3-using-rvm/

now i am not able to run any commands related to puppet. if i try to get puppet version, its throwing the below error:

[root@localhost ~]# puppet --version
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/site_ruby/1.8/puppet/module.rb:3
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/files.rb:1
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/templatewrapper.rb:1
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/scope.rb:6
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/site_ruby/1.8/puppet/parser/methods.rb:2

**Comment by ram2valar** [comment]
now the ruby version is:

[root@localhost ~]# ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
[root@localhost ~]#

**Comment by garethr** [comment]
You've likely got two versions of ruby and two versions of Puppet installed at this point, and your path is configured to locate the older ones, rather than those from the puppet-agent installer. You should be able to find those here:

```
/opt/puppetlabs/bin/puppet --version
/opt/puppetlabs/puppet/bin/ruby --version
```

Some more context. http://docs.puppetlabs.com/puppet/latest/reference/whered_it_go.html#nix-executables-are-in-optpuppetlabsbin

Note that this means you'll need to install the gems into that ruby with

    /opt/puppetlabs/puppet/bin/gem install aws-sdk-core retries

**Comment by ram2valar** [comment]
Hi Gare,

I don't have two version of puppet at my machine. I installed only one from the puppet labs repo which installed the version of 3.8.3. It seems i didn't install latest one i.e. puppet 4.x. As 4.x version is not installed, puppet is not located under /opt/puppetlabs/bin path.

[root@localhost ~]# find / -name puppet 2>/dev/null
/usr/share/puppet
/usr/share/puppet/ext/logcheck/puppet
/usr/lib/ruby/site_ruby/1.8/puppet
/usr/lib/ruby/site_ruby/1.8/puppet/util/rdoc/generators/template/puppet
/usr/lib/ruby/site_ruby/1.8/puppetx/puppet
/usr/bin/puppet
/etc/rc.d/init.d/puppet
/etc/puppet
/etc/sysconfig/puppet
/etc/logrotate.d/puppet
/var/run/puppet
/var/log/puppet
/var/lib/puppet

do i need to first install ruby of version greater than 2 before installing puppet master in my server.

I am referring the below link:

http://docs.puppetlabs.com/puppet/4.2/reference/system_requirements.html

Thanks,
Ram.

**Comment by sagrahari1** [comment]
I am also facing the same issue and keep getting error "Could not find a suitable provider for ec2_instance" while running a pp file to create ec2 instance. Installed version are
Ruby - ruby 1.9.3p484 (2013-11-22 revision 43786)
puppet - 4.4.1
puppetlabs-aws (v1.4.0)
I installed aws module using "/opt/puppetlabs/puppet/bin# gem install aws-sdk-core retries".
Everything seems correct configuration, still keep getting the same error.
Please help
