### ISSUE TITLE
ec2_instance tag change

### ISSUE THREAD

**Issue by vbarba** [puppetlabs/puppetlabs-aws#234]
Hi,

I am trying to modify a tag value on a running instance without success. Is this a limitation? On the documentation doesn't specify that this parameter is "creation only".

Kind Regards,
Victor

**Comment by evidex** [comment]
Tags can be edited via the console post creation, so I would imagine that this should be possible.

**Comment by vbarba** [comment]
yes @evidex, I agree with you that it should be possible. I don't know if I am doing something wrong or is not implemented.

**Comment by garethr** [comment]
@vbarba this should work, for instance this is tested in the acceptance tests here: https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/acceptance/instance_spec.rb#L225

If you could post some code examples and the output happy to help.

**Comment by garethr** [comment]
I'll close this issue as it's not been responded to since I posted a reply. If you're still having an issue please do reopen with some more details.
