### ISSUE TITLE
Error: Could not find a suitable provider for ec2_securitygroup

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#235]
Hi,

I installed latest version of puppet and ruby.

[root@puppetmaster tests]# puppet --version
2015-10-13 03:29:38.732727 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
4.2.2
[root@puppetmaster tests]# ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]

i set AWS_region and AWS access keys in environment variables.

sample test.pp file:

ec2_securitygroup { 'test-sg':
  ensure      => present,
  description => 'Security group for testing',
  ingress     => [{
    protocol => 'tcp',
    port     => 80,
    cidr     => '0.0.0.0/0'
  }],
}

when i applied this test.pp, i am getting following error:

[root@puppetmaster tests]# puppet apply test.pp --test
2015-10-13 03:31:21.397806 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Notice: Compiled catalog for puppetmaster.datami.com in environment production in 0.40 seconds
Info: Applying configuration version '1444687283'
Error: Could not find a suitable provider for ec2_securitygroup
Notice: Applied catalog in 0.10 seconds
[root@puppetmaster tests]#

**Comment by garethr** [comment]
It sounds like you're probably missing the required gems for the module. You can see the details in the README: https://github.com/puppetlabs/puppetlabs-aws#installing-the-aws-module. Depending on how you installed Ruby you'll want something like:

    gem install aws-sdk-core retries

**Comment by ram2valar** [comment]
Hi Gare,

I installed gem as below:

[root@puppetmaster vpc-example]# which gem
/opt/puppetlabs/puppet/bin/gem
[root@puppetmaster vpc-example]# /opt/puppetlabs/puppet/bin/gem install aws-sdk-core retries
Fetching: jmespath-1.1.3.gem (100%)
Successfully installed jmespath-1.1.3
Fetching: aws-sdk-core-2.1.29.gem (100%)
Successfully installed aws-sdk-core-2.1.29
Parsing documentation for aws-sdk-core-2.1.29
Installing ri documentation for aws-sdk-core-2.1.29
Parsing documentation for jmespath-1.1.3
Installing ri documentation for jmespath-1.1.3
Done installing documentation for aws-sdk-core, jmespath after 4 seconds
Fetching: retries-0.0.5.gem (100%)
Successfully installed retries-0.0.5
Parsing documentation for retries-0.0.5
Installing ri documentation for retries-0.0.5
Done installing documentation for retries after 0 seconds
3 gems installed

now i am getting following error:

[root@puppetmaster vpc-example]# puppet apply test.pp --modulepath /etc/puppetlabs/code/environments/production/modules/aws/examples/vpc-example --test
2015-10-13 05:12:30.371971 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Notice: Compiled catalog for puppetmaster.datami.com in environment production in 0.52 seconds
Info: Applying configuration version '1444693352'
Error: Could not run: Puppet detected a problem with the information returned from AWS
when looking up ec2_vpc in us-east-1. The specific error was:

AWS was not able to validate the provided access credentials

Rather than report on ec2_vpc resources in an inconsistent state we have exited.
This could be because some other process is modifying AWS at the same time.
[root@puppetmaster vpc-example]# puppet resource ec2_vpc
2015-10-13 05:12:47.495513 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Error: Could not run: Puppet detected a problem with the information returned from AWS
when looking up ec2_vpc in us-east-1. The specific error was:

AWS was not able to validate the provided access credentials

Rather than report on ec2_vpc resources in an inconsistent state we have exited.
This could be because some other process is modifying AWS at the same time.
[root@puppetmaster vpc-example]#

**Comment by ram2valar** [comment]
I configured the AWS credentials:

[root@puppetmaster vpc-example]# cat ~/.aws/credentials
[default]
aws_access_key_id = xxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxx
[root@puppetmaster vpc-example]#

still i am getting the above said error. however i am able to run using the above configured AWS credentials to retrieve region information:

[Ramkumar-Nagaraj-MacBook-Pro:aws-ec2-scripts rnagaraj]$ aws ec2 describe-regions
{
    "Regions": [
        {
            "Endpoint": "ec2.eu-west-1.amazonaws.com",
            "RegionName": "eu-west-1"
        },
        {
            "Endpoint": "ec2.ap-southeast-1.amazonaws.com",
            "RegionName": "ap-southeast-1"
        },
        {
            "Endpoint": "ec2.ap-southeast-2.amazonaws.com",
            "RegionName": "ap-southeast-2"
        },
        {
            "Endpoint": "ec2.eu-central-1.amazonaws.com",
            "RegionName": "eu-central-1"
        },
        {
            "Endpoint": "ec2.ap-northeast-1.amazonaws.com",
            "RegionName": "ap-northeast-1"
        },
        {
            "Endpoint": "ec2.us-east-1.amazonaws.com",
            "RegionName": "us-east-1"
        },
        {
            "Endpoint": "ec2.sa-east-1.amazonaws.com",
            "RegionName": "sa-east-1"
        },
        {
            "Endpoint": "ec2.us-west-1.amazonaws.com",
            "RegionName": "us-west-1"
        },
        {
            "Endpoint": "ec2.us-west-2.amazonaws.com",
            "RegionName": "us-west-2"
        }
    ]
}
[Ramkumar-Nagaraj-MacBook-Pro:aws-ec2-scripts rnagaraj]$

**Comment by ram2valar** [comment]
never mind i found the root cause for the issue. there was a time non-sync. now i synced the time, post that able to create sample-vpc using puppet module
