### ISSUE TITLE
not paging through aws api resource results

### ISSUE THREAD

**Issue by dharmabruce** [puppetlabs/puppetlabs-aws#236]
We discovered that this puppetlabs-aws module is only using the first batch of returned AWS resources and not iterating to collect all resources. We have more than 100 resource records in a route53 zone but since the Puppet::Provider::Route53Record self.instances method only calls route53_client.list_resource_record_sets once, and our zone has more than 100 records, we cannot manage all of our records. ([AWS API doc for route53_client.list_resource_record_sets](http://docs.aws.amazon.com/sdkforruby/api/Aws/Route53/Client.html#list_resource_record_sets-instance_method).)

Almost all AWS resource APIs return paged results but this module doesn't seem to iterate to collect all resources in any case that I can find in the code. Unless I'm missing something?

**Comment by benglersc** [comment]
+1 
We're having the same problem with a zone which has almost 1000 records. Is there an easy fix for this?

**Comment by DoctahPopp871** [comment]
I actually just ran into this. We have a route53_zone with almost 1,000 records. My thought is that if you change or specify the MaxItems value for the list_resource_record_sets @ line 10 on the route53_record.rb file you can get past the paging. Trying to see where I can get with this type of change.

**Comment by DoctahPopp871** [comment]
This looks like the path to resolution 
To retrieve all the records in a HostedZone, first pause any processes making calls to ChangeResourceRecordSets. Initially call ListResourceRecordSets without a Name and Type to get the first page of record sets. For subsequent calls, set Name and Type to the NextName and NextType values returned by the previous response.

**Comment by garethr** [comment]
Thanks for flagging this, it's a bug in the Route53 provider specifically, the other providers should deal with this correctly.

The AWS response object is enumerable (http://docs.aws.amazon.com/sdkforruby/api/index.html#Paging_Responses), so in the `ec2_instance` type the collection is all done in the block: https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/provider/ec2_instance/v2.rb#L23-L32

But in the Route53 provider this is done incorrectly: https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/provider/route53_record.rb#L10

The fix here is to chain this together using each, at which point the underlying client will page though the responses, making multiple API requests as needed.

When I get a moment I'll fix this, but wanted to post up something as I might not get to it immediately.

**Comment by dharmabruce** [comment]
Oh, good, glad to know I wasn't going crazy and that it's limited to the Route53 provider. Thanks for noticing and linking to a simple workaround.

**Comment by DoctahPopp871** [comment]
Thanks for the point of reference Gareth. We have implemented the paging change and it is looking good thus far. Ill fork this repo and get a pull request going.

**Comment by DoctahPopp871** [comment]
https://github.com/puppetlabs/puppetlabs-aws/pull/245

This should do the trick.

**Comment by garethr** [comment]
Fixed in master. Thanks all for reporting and to @DoctahPopp871 for testing the fix.
