### ISSUE TITLE
need sample snippet for db_subnet creating by declared variables

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#240]
Hi,

I am able to create subnet using below snippet. however the values are hardcoded. i wish to call the variables which is being assigned by these hardcoded values so that i can reuse for other db setup.

ec2_vpc_subnet { 'test-subnet':
  ensure            => present,
  region            => 'us-east-1',
  vpc               => 'test-vpc',
  cidr_block        => '10.65.61.0/24',
  availability_zone => 'us-east-1a',
  tags              => {
        name => 'test-subnet',
 }
}

If i need to create multiple subnets, i don't want to repeat few parameters by retyping such as ensure, region, vac and availability zone. Instead i need to define a class for declaring these parameters and passing these parameters as variables.

Requirement:

ec2_vpc_subnet { 'test-subnet1':
  ensure            => present,
  region            => 'us-east-1',
  vpc               => 'tets-vpc',
  cidr_block        => '10.64.61.0/24',
  availability_zone => 'us-east-1a',
  tags              => {
        name => 'test-subnet1',
 }
}

ec2_vpc_subnet { 'test-subnet2':
  ensure            => present,
  region            => 'us-east-1',
  vpc               => 'test-vpc',
  cidr_block        => '10.64.62.0/24',
  availability_zone => 'us-east-1a',
  tags              => {
        name => 'test-subnet2',
 }
}

ec2_vpc_subnet { 'test-subnet3':
  ensure            => present,
  region            => 'us-east-1',
  vpc               => 'test-vpc',
  cidr_block        => '10.64.63.0/24',
  availability_zone => 'us-east-1a',
  tags              => {
        name => 'test-subnet3',
 }
}

Could you give me a snippet with declaring variables and inheriting that class instead of hardcoding these values multiple times.

Thanks,
Ram.

**Comment by garethr** [comment]
There are a few ways of doing this work of thing with Puppet. One is called [Resource Defaults](https://docs.puppetlabs.com/puppet/latest/reference/lang_defaults.html). You could pull out defaults like so.

```puppet
Ec2_vpc_subnet {
  ensure => present,
  region => 'us-east-1',
  vpc => 'tets-vpc',
  cidr_block => '10.64.61.0/24',
  availability_zone => 'us-east-1a',
  tags => {
    name => 'test-subnet1',
  }
}

ec2_vpc_subnet { 'test-subnet1':
  cidr_block => '10.64.61.0/24',
  tags => {
    name => 'test-subnet1',
  }
}

ec2_vpc_subnet { 'test-subnet2':
  cidr_block => '10.64.62.0/24',
  tags => {
    name => 'test-subnet2',
  }
}

ec2_vpc_subnet { 'test-subnet3':
  cidr_block => '10.64.63.0/24',
  tags => {
    name => 'test-subnet3',
  }
}
```

The other approach would be similar to what you describe, using a [defined type](https://docs.puppetlabs.com/puppet/latest/reference/lang_defined_types.html).

You can see a few examples of other approaches in the examples folder: [using hiera](https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/hiera-example), [defined types](https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/create-your-own-abstractions) or [just with puppet code](https://github.com/puppetlabs/puppetlabs-aws/blob/master/examples/data-driven-manifests/init.pp).
