### ISSUE TITLE
not able to create subnet using resource declaration

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#242]
HI,

I am not able to create subnet in aws. following is my init.pp where i have declared the common variables and subnet creation steps.

init.pp:
define subnet_creation(
  $customer = 'devops',
  $company = 'test',
  $region = 'us-east-1',
  $availability_zone = 'us-east-1a',
  $index = '1',
  $priv_api_category = 'apiservers',
  $priv_db_category = 'dbservers',
  $pub_category = 'public',
  $priv_category = 'private',
  $redundant = 'yes',
  $redundant_availabilty_zone = 'us-east-1c',
  $ensure = 'present',
) {

    if $region == "us-east-1" {
        $region_name = 'nvirginia'
    }    
    elsif $region == "us-west-1" {
        $region_name = 'ncalifornia'
    }
    elsif $region == "us-west-2" {
        $region_name = 'oregon'
    }
    elsif $region == "eu-west-1" {
        $region_name = 'ireland'
    }
    elsif $region == "eu-central-1" {
        $region_name = 'frankfurt'
    }
    elsif $region == "ap-southeast-1" {
        $region_name = 'singapore'
    }
    elsif $region == "ap-southeast-2" {
        $region_name = 'sydney'
    }
    elsif $region == "ap-northeast-1" {
        $region_name = 'tokyo'
    }
    elsif $region == "sa-east-1" {
        $region_name= 'saopaulo'
    }
    else {
          warning('Invalid region specified in definition.')
    }

ec2_vpc_subnet { "${customer}-${company}-${priv_category}-${priv_db_category}-${region_name}-${index}":
  ensure            => $ensure,
  region            => $region,
  vpc               => $customer-$company-$region_name,
  cidr_block        => '10.23.61.0/24',
  availability_zone => $availability_zone,
  tags              => {
                          name => "${customer}-${company}-${priv_category}-${priv_db_category}-${region_name}-${index}",
                        }
                }
  }

when i applied this manifest, its not printing any error/message. 

[ec2-user@xxxxxxxxx manifests]$ puppet apply init.pp --test
2015-10-19 13:08:50.022361 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Notice: Compiled catalog for xxxxxxxxxxxx in environment production in 0.58 seconds
Info: Applying configuration version '1445260131'
Notice: Applied catalog in 0.02 seconds

upon checking in AWS console, db subnet was not created. i already exported AWS keys information.

Could you assist on this.

Thanks,
Ram.

**Comment by garethr** [comment]
I'm presuming this is the same issue as #243. I'll close at least until we resolve that one.

**Comment by ram2valar** [comment]
Hi Gare,

Dont close this issue #242. still i am not able t create subnets using declaration. i pasted the init.pp, could you please assist on this.

**Comment by garethr** [comment]
If you could provide the output from the command run with the `--debug` flag.

Looking at the code, it looks like you have a defined type but you haven't realised it? That would explain why you're not seeing the subnet created. eg. you never actually call `subnet_creation`.

**Comment by ram2valar** [comment]
Hi Gare,

Could you share me a snippet of this requirement by testing in your setup.

**Comment by garethr** [comment]
@ram2valar you can see a working example of using a defined type in this example https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/create-your-own-abstractions

Note the init.pp manifest which uses the defined type.
