### ISSUE TITLE
not able to execute aws examples manifests in aws instance

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#243]
Hi,

Following are the version of puppet, ruby and gem installed in my aws ec2 instance.

[ec2-user@xxxxxxx vpc-example]$ /opt/puppetlabs/puppet/bin/ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
[ec2-user@xxxxxxx vpc-example]$ /opt/puppetlabs/puppet/bin/gem --version
2.2.5
[ec2-user@xxxxxxxx vpc-example]$ /opt/puppetlabs/puppet/bin/puppet --version
2015-10-19 13:52:51.913006 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
4.2.2
[ec2-user@xxxxxxxx vpc-example]$ ls
README.md  destroy.pp  init.pp  vpn.pp  vpn_destroy.pp
[ec2-user@xxxxxxx vpc-example]$

I was trying to execute vpc creation of above example, received following error:

[ec2-user@xxxxxxxxx vpc-example]$ puppet apply init.pp --test
2015-10-19 13:50:10.373667 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Error: Evaluation Error: Error while evaluating a Resource Statement, Invalid resource type ec2_vpc at /etc/puppetlabs/code/environments/production/modules/aws/examples/vpc-example/init.pp:1:1 on node xxxxxxxxxx
[ec2-user@xxxxxxx vpc-example]$

server time is in UTC format.

could you please assist in this issue.

Thanks,
Ram.

**Comment by garethr** [comment]
Hi @ram2valar. My guess is the module or it's dependencies haven't been installed. Could you run with `--debug` and report the result?

**Comment by ram2valar** [comment]
Hi Gare,

Issue was i didnt execute this with sudo. upon using sudo able to create ec2 resources using this module in ec2 instance, this can be closed. Thanks for turning back.
