### ISSUE TITLE
how to allow all traffic in security group creation

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#244]
Hi,

I am trying to create a security group which allows all traffic.

Ec2_securitygroup {
  region => 'us-east-1',
  ensure => 'present',
}
ec2_securitygroup { 'devops-test-nvirginia':
                description => 'Test Security Group',
                ingress     => [{
                                security_group => 'devops-test-nvirginia',
                                protocol => ALL,
                                port     => ALL,
                                }],
                tags => {
                        name => 'devops-test-nvirginia',
                },
}

Security group created however inbound rule not set, as i am getting below error:

[ec2-user@ecxxxxxx manifests]$ sudo puppet apply testgroup.pp --test
2015-10-21 12:47:05.000547 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Notice: Compiled catalog for ecxxxxxxx.compute-1.amazonaws.com in environment production in 0.56 seconds
Info: Applying configuration version '1445431626'
Info: Checking if security group devops-test-nvirginia exists in region us-east-1
Info: Creating security group devops-test-nvirginia in region us-east-1
Error: Could not set 'present' on ensure: undefined method `to_i' for All[]{:name=>""}:Puppet::Resource at 7:/etc/puppetlabs/code/environments/production/manifests/testgroup.pp
Error: Could not set 'present' on ensure: undefined method `to_i' for All[]{:name=>""}:Puppet::Resource at 7:/etc/puppetlabs/code/environments/production/manifests/testgroup.pp
Wrapped exception:
undefined method `to_i' for All[]{:name=>""}:Puppet::Resource
Error: /Stage[main]/Main/Ec2_securitygroup[devops-test-nvirginia]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `to_i' for All[]{:name=>""}:Puppet::Resource at 7:/etc/puppetlabs/code/environments/production/manifests/testgroup.pp
Notice: Applied catalog in 13.95 seconds

Does this module supports inbound rule to allow all traffic.

Thanks,
Ram.

**Comment by garethr** [comment]
This is a little underdocumented, but for future reference the acceptance and spec tests are a good guide. For instance https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/unit/ingress_rules_spec.rb and https://github.com/puppetlabs/puppetlabs-aws/blob/master/spec/acceptance/securitygroup_spec.rb.

The following should expand to all ports and protocols I think.

```puppet
security_group => 'devops-test-nvirginia',
  cidr => '0.0.0.0/0',
}],
```

**Comment by ram2valar** [comment]
Hi Gare,

Applied that inbound rule, it created rule for only tcp, udp and icmp protocols for all ports starting 0-65535. its creating three lines for setting these rules. whereas in AWS GUI, with a single line we can accomplish this by selecting Type as 'ALL Traffic'.

we need same to be implemented using this module in single line for 'All traffic' rather than three lines.

Thanks,
Ram.

**Comment by garethr** [comment]
@ram2valar I'm afraid it's not possible exactly as you describe at the moment, although as noted it is possible. I'd be more than happy to see a PR that expands that interface however but I'll close this specific issue for now
