### ISSUE TITLE
how to assign multiple tags for ec2 instance

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#247]
Following is the instance creation manifest file,

ec2_instance { 'devops-test-haproxy-nvirginia-1a1':
  ensure            => present,
  region            => 'us-east-1',
  availability_zone => 'us-east-1a',
  image_id          => 'ami-cf1066aa',
  instance_type     => 't1.micro',
  monitoring        => false,
  key_name          => 'devops-puppetm-nvirginia',
  security_groups   => ['devops-test-haproxy-nvirginia-1a', 'puppets'],
  private_ip_address  => '10.23.0.20',
  subnet            => 'devops-test-public-nvirginia-1a1',
  user_data         => template('/etc/puppetlabs/code/environments/production/modules/puppetagent.sh.erb'),
  tags              => {
    "tag_name" => 'devops-test-haproxy-nvirginia-1a1',
    "tag_type" => 'devops-test-haproxy-nvirginia-1a1',
    "tag_stackdriver_monitor" => false,
  }
}

however tags (name,type and stackdriver_monitor) not filled with the value which i set. those are empty and received below error:
error:
Error: Could not set 'present' on ensure: expected params[:tags][2][:value] to be a string at 1:/etc/puppetlabs/code/environments/production/manifests/instance_creation.pp
Error: Could not set 'present' on ensure: expected params[:tags][2][:value] to be a string at 1:/etc/puppetlabs/code/environments/production/manifests/instance_creation.pp
Wrapped exception:
expected params[:tags][2][:value] to be a string
Error: /Stage[main]/Main/Ec2_instance[devops-test-haproxy-nvirginia-1a1]/ensure: change from absent to present failed: Could not set 'present' on ensure: expected params[:tags][2][:value] to be a string at 1:/etc/puppetlabs/code/environments/production/manifests/instance_creation.pp
Notice: Applied catalog in 12.01 seconds
[ec2-user@ec2-52-1-28-147 manifests]$

how to specify multiple tags for a instance.

**Comment by garethr** [comment]
Tags need tp be strings, but we're not catching the error at the type level at the moment it looks like.
Instead of:

   "tag_stackdriver_monitor" => false,

Try:

    tag_stackdriver_monitor => 'false',

**Comment by ram2valar** [comment]
Hi Gare,

Able to add multiple tags by following below snippet, we have to enclose those in quotation.

tags              => {
    'Name' => 'devops-test-haproxy-nvirginia-1a1',
    'Type' => 'devops-test-haproxy-nvirginia-1a1',
    'stackdriver_monitor' => 'false',
  }

**Comment by garethr** [comment]
Thanks for letting us know.
