### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#248]
HI,

I removed old certificate of puppet master, regenerated new certificates for puppet master and puppet clients. If i execute VPC samples in puppet master (already aws module configured, pre-requisite aws-sdk, ruby-gems and retries installed), getting certificate verify failed.

[ec2-user@haprox1 vpc-example]$ sudo puppet apply test.pp --test
2015-10-28 13:45:12.022702 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C
Notice: Compiled catalog for haprox1 in environment production in 0.70 seconds
Info: Applying configuration version '1446039913'
Error: Failed to apply catalog: SSL_connect returned=1 errno=0 state=error: certificate verify failed
[ec2-user@haprox1 vpc-example]$ pwd
/etc/puppetlabs/code/environments/production/modules/aws/examples/vpc-example

how can i make this aws module to be working in this puppet master instead of recreating the whole box.

Thanks,
Ram.

**Comment by garethr** [comment]
Hi @ram2valar. For more general Puppet questions it's probably best to ask on the puppet-users mailing list, or on http://ask.puppetlabs.com/questions/.

This module is designed for managing instances and other EC2 resources, so the examples are focused on that usecase only I'm afraid.
