### ISSUE TITLE
ec2 instance not updated with user data file

### ISSUE THREAD

**Issue by ram2valar** [puppetlabs/puppetlabs-aws#254]
Hi,

I tried creating instance using this puppet module. Instance is getting created however, user-data file is not getting executed during instance creation.

Snippet:
ec2_instance { 'devops-sni-nvirginia-1a1':
  ensure            => present,
  region            => 'us-east-1',
  availability_zone => 'us-east-1a',
  image_id          => 'ami-cf1066aa',
  instance_type     => 't1.micro',
  monitoring        => false,
  key_name          => 'devops-gw-nvirginia',
  security_groups   => ['devops-sni-nvirginia-1a', 'puppets'],
  private_ip_address  => 'xx.yy.zz.aa',
  subnet            => 'devops-public-nvirginia-1a1',
  user_data         => template('/etc/puppetlabs/code/environments/devopstest/modules/aws/templates/puppetagent.sh.erb'),
  tags              => {
    'Name' => 'devops-sni-nvirginia-1a1',
    'Type' => 'snigw-1a1',
    'stackdriver_monitor' => 'false',
  }
}

snippet of user-data script: puppetagent.sh.erb
#!/bin/bash
set -e -x
yum update -y
rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
yum install -y puppet
echo "
[main]
certname = devops-sni-1a1
server = puppet
environment = production
configtimeout = 600
" >> /etc/puppetlabs/puppet/puppet.conf
service puppet restart

 puppetagent.sh.erb is located in /etc/puppetlabs/code/environments/devopstest/modules/aws/templates/ in puppet master.

following is the syntax which specified in instance creation:

user_data         => template('/etc/puppetlabs/code/environments/devopstest/modules/aws/templates/puppetagent.sh.erb'),

this is not getting executed but instance is created. could you assist this.

Thanks,
Ram.

**Comment by garethr** [comment]
`template` will search on the template path, rather than the full file system path. You can find the [function documentation here](https://docs.puppetlabs.com/references/latest/function.html#template). So in this case the path should probably be `aws/templates/puppetagent.sh.erb`

Given the template isn;t being passed any variables here you could also just use [file](https://docs.puppetlabs.com/references/latest/function.html#file).

Note as well that it's typical to creat your own modules and store templates like this in your own namespace, rather than add them into the AWS module. Doing the later means you'll find updating difficult as your template will be overridden.

**Comment by ram2valar** [comment]
HI gare,

I am having two environment, one is production and other is devopstest. in this case how can i specify the template path and where can i keep this template file.

**Comment by garethr** [comment]
@ram2valar you'll want to create your own module with a files or template directory, and then install your module into both of your environments. This is part of the reason for what you're trying to do not working, environments are meant to be isolated, so accessing a file from outside the environment would break that isolation.

**Comment by tarunmangla07** [comment]
I am also going through the same error, the instance is created but the user_data script is not getting executes @garethr, 
I have stored the windows-pe.erb file inside /etc/puppetlabs/code/environments/production/modules/aws/templates/windows-pe.erb'
i am giving the manifests as 
user_data =>template(aws/windows-pe.erb)
i have taken the reference from your puppetlabs-aws github document

Can you suggest me where i am going wrong.
