### ISSUE TITLE
ec2_instance - Add ability to set 'Tenancy' in placement configuration options.

### ISSUE THREAD

**Issue by jknaggs** [puppetlabs/puppetlabs-aws#259]
We would like to have the ability to set 'Tenancy' on individual EC2 Instances rather than setting this at a VPC level. We have a licensing requirement to launch specific instances on 'Dedicated' tenancy.

Example: 

ec2_instance { 'name-of-instance':
  ensure            => present,
  region            => 'us-east-1',
  availability_zone => 'us-east-1a',
**  tenancy     => 'dedicated' **
  image_id          => 'ami-123456',
....
}

Config example from SDK.

  placement: {
    availability_zone: "String",
    group_name: "String",
    ** tenancy: "default", # accepts default, dedicated, host **
    host_id: "String",
    affinity: "String",
  },
....

**Comment by garethr** [comment]
Their is some unfinished work on this in https://github.com/puppetlabs/puppetlabs-aws/pull/147

**Comment by jknaggs** [comment]
My apologies, I didnt go over the existing Pull Requests thoroughly. Look forward to the enhancement.

**Comment by daveseff** [comment]
@jknaggs Looks like PR #147 has been abandoned so I'll try to pick it up. Any questions let me know as I sit about 8 meters from you ;)

**Comment by tphoney** [comment]
#295 should resolve this issue.
