### ISSUE TITLE
Puppet wants to start a running instance

### ISSUE THREAD

**Issue by zleswomp** [puppetlabs/puppetlabs-aws#262]
Using a manifest produced with `puppet resource ec2_instance`, I receive the following error:

```
Notice: /Stage[main]/Main/Ec2_instance[cassandra1]/ensure: current_value running, should be running (noop)
```

If the instance is already running (which it is), puppet should not attempt to start it.

**Comment by DoctahPopp871** [comment]
Pretty sure that has been resolved with this https://github.com/puppetlabs/puppetlabs-aws/pull/251/commits

**Comment by zleswomp** [comment]
Ah, this appears so.  Running from master no longer has this issue.  Could we get a release cut to the forge for future `puppet module install`s?

**Comment by garethr** [comment]
@zleswomp perfect timing. We should be releasing 1.3.0 anytime soon, it was tagged just yesterday: https://github.com/puppetlabs/puppetlabs-aws/tree/1.3.0

**Comment by zleswomp** [comment]
Thanks @garethr!
