### ISSUE TITLE
ec2_instance reports incorrect region metaparameter when using config file

### ISSUE THREAD

**Issue by aharden** [puppetlabs/puppetlabs-aws#264]
When setting `region = us-east-1` in  `$confdir/puppetlabs_aws_configuration.ini` as documented in https://github.com/puppetlabs/puppetlabs-aws/pull/263 and running `puppet resource ec2_instance`, I get a list of our current EC2 instances in us-east-1, but each of them have a `region` parameter of `eu-west-1`.  When running the `puppet resource` command with both the REGION environment variable and configuration file region set to `us-east-1`, the correct `us-east-1` metaparameter is shown for the listed instances.

**Comment by daveseff** [comment]
Submitted PR #275 that fixes this issue.

**Comment by aharden** [comment]
@daveseff Thanks!

**Comment by DavidS** [comment]
Merged. Thanks everyone!
