### ISSUE TITLE
Security group ingress rules don't support ICMP types

### ISSUE THREAD

**Issue by danielparks** [puppetlabs/puppetlabs-aws#266]
AWS supports ingress rules for specific ICMP types. puppetlabs-aws always sets ICMP to all types.

AWS puts ICMP types in `FromPort`, and expects -1 in `ToPort`. Here's a listing from a security group created in the console:

~~~
➜  aws ec2 describe-security-groups --group-ids sg-2a67724e | jq '.SecurityGroups[0].IpPermissions'
[
  {
    "PrefixListIds": [],
    "FromPort": 10,
    "IpRanges": [
      {
        "CidrIp": "0.0.0.0/0"
      }
    ],
    "ToPort": -1,
    "IpProtocol": "icmp",
    "UserIdGroupPairs": []
  },
  {
    "PrefixListIds": [],
    "FromPort": 0,
    "IpRanges": [
      {
        "CidrIp": "0.0.0.0/0"
      }
    ],
    "ToPort": -1,
    "IpProtocol": "icmp",
    "UserIdGroupPairs": []
  }
]
~~~

That allows only ICMP type 0 (Echo reply) and type 10 (Router selection).

The offending code is [/puppet/provider/ec2_securitygroup/v2.rb  in `prepare_ingress_for_api `](https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/provider/ec2_securitygroup/v2.rb#L150-L151):
~~~ruby
      permission[:to_port] = protocol == 'icmp' ? -1 : to_port.to_i
      permission[:from_port] = protocol == 'icmp' ? -1 : from_port.to_i
~~~

Please let me know if there's any more information I can provide! Thanks!

**Comment by daveseff** [comment]
This is one of my resource definitions which works quite well:

    ec2_securitygroup { 'qa':
      ensure      => present,
      description => 'QA',
      vpc => $vpc,
      ingress     => [
         ...
         {cidr => '10.10.0.0/16', from_port => '-1',    protocol => 'icmp', to_port => '-1'},
         ...
      ],
    }

**Comment by danielparks** [comment]
@daveseff that doesn't filter on ICMP type (sometimes called port). I should be able to only allow, say, type 0.

**Comment by daveseff** [comment]
I have submitted PR #274 to fix your problem.

**Comment by danielparks** [comment]
Fixed by @daveseff!
