### ISSUE TITLE
puppet node_aws command not present

### ISSUE THREAD

**Issue by deepagargit** [puppetlabs/puppetlabs-aws#268]
I have installed puppet aws module as specified in this github.

But node_aws sub-command is not shown in puppet help.

The aws module is installed

 pwd
/home/centos/.puppet/modules/aws
$ ls
bin           checksums.json  CONTRIBUTING.md  fixtures  Guardfile  LICENSE        Rakefile   spec
CHANGELOG.md  contrib         examples         Gemfile   lib        metadata.json  README.md  tests

But puppet didn;t get node_aws subcommand.
Is there any PATH setting require or what could be missing factor?

 puppet help | grep node
  node              View and manage node definitions.
  resource_type     View classes, defined resource types, and nodes from all manifests.

**Comment by garethr** [comment]
`node_aws` is not part of the AWS module I'm afraid, it was part of the (now deprecated) cloud_provisioner: https://forge.puppetlabs.com/puppetlabs/cloud_provisioner
