### ISSUE TITLE
Passing block_devices hash with puppet RAL commands

### ISSUE THREAD

**Issue by szemlyanoy** [puppetlabs/puppetlabs-aws#279]
Hey,

I'm trying to launch instances using command
_puppet resource ec2_instance instance1  <..some_required_params> block_devices:[{'delete_on_termination' => 'true', 'device_name' => '/dev/sda'}]_

but got

_Error: Could not run: Invalid parameter setting block_devices:[{delete_on_termination

Am i passing hash badly wrong?

Thanks
Sergey

**Comment by garethr** [comment]
@szemlyanoy I'm afraid puppet resource doesn't allow for more complex data structures like arrays and hashes. You're best bet for this case is to use `puppet -e`, for instance replaced the notify here with a valid ec2_instance resource.

```
puppet -e 'notify { "We are running on $operatingsystem": }'
```
