### ISSUE TITLE
Enable ec2_vpc to create vpc's with DNS resolution and hostname

### ISSUE THREAD

**Issue by mrzarquon** [puppetlabs/puppetlabs-aws#286]
Currently we don't do anything around enable dns, making it difficult to create a new vpc and use it immediately.

**Comment by ayen-tibco** [comment]
+1

**Comment by ahenroid** [comment]
I submitted https://github.com/puppetlabs/puppetlabs-aws/pull/421

**Comment by zleswomp** [comment]
#421 has been merged.  Closing.
