### ISSUE TITLE
Documentation might be out of date 

### ISSUE THREAD

**Issue by Sher-Chowdhury** [puppetlabs/puppetlabs-aws#297]
I think the documentation needs updating with respect to how to install gems. See:

https://ask.puppet.com/question/25719/getting-error-could-not-find-a-suitable-provider-error-message-when-puppetlabs-aws-module/?answer=25725#post-id-25725

**Comment by ahenroid** [comment]
Thanks, @Sher-Chowdhury. I'm doing some house cleaning now and submitted https://github.com/puppetlabs/puppetlabs-aws/pull/423 to address this.

**Comment by zleswomp** [comment]
PR #423 has been merged.

**Comment by ahenroid** [comment]
Thanks @zleswomp!
