### ISSUE TITLE
Error: Could not find a suitable provider for ec2_instance : puppet Enterprise 2016.1

### ISSUE THREAD

**Issue by sagrahari1** [puppetlabs/puppetlabs-aws#298]
I  keep getting error "Could not find a suitable provider for ec2_instance" while running a pp file to create ec2 instance from puppet Enterprise 2016.1 .
Installed version are
Ruby - ruby 1.9.3p484 (2013-11-22 revision 43786)
puppet - 4.4.1
puppetlabs-aws (v1.4.0)
I installed aws module using "/opt/puppetlabs/puppet/bin# gem install aws-sdk-core retries".
Everything seems correct configuration, still keep getting the same error. I followed the suggestions given in similar threads but it is not helping
Please advise.

**Comment by zleswomp** [comment]
If you are using puppetserver, you might need to install the relevant gems in the using the puppetserver command.  `/opt/puppetlabs/bin/puppetserver gem` and then restart the server.

**Comment by sagrahari1** [comment]
I am using Puppet Enterprise and have already installed gem using command
/opt/puppetlabs/puppet/bin gem install aws-sdk-core retries
Output from gem list :- 

/opt/puppetlabs/puppet/bin$ gem list

*** LOCAL GEMS ***

aws-sdk (2.2.37)
aws-sdk-core (2.2.37)
aws-sdk-resources (2.2.37)
jmespath (1.2.4)
json_pure (1.8.3)
retries (0.0.5)

I restarted the pe-puppetserver service as well but still same error

**Comment by zleswomp** [comment]
Check the path on the command I gave above.  Its the `puppetserver` gem command that you need to be using.

**Comment by sagrahari1** [comment]
installed using below command
/opt/puppetlabs/bin# puppetserver gem install aws-sdk-core retries
Fetching: json_pure-1.8.3.gem (100%)
Successfully installed json_pure-1.8.3
Fetching: jmespath-1.2.4.gem (100%)
Successfully installed jmespath-1.2.4
Fetching: aws-sdk-core-2.2.37.gem (100%)
Successfully installed aws-sdk-core-2.2.37
Fetching: retries-0.0.5.gem (100%)
Successfully installed retries-0.0.5
4 gems installed
restarted pe-puppetserver service but still getting same error

**Comment by sagrahari1** [comment]
Hi zleswomp,
Any pointer please.

**Comment by zleswomp** [comment]
Have you written the access keys anywhere?  I've not looked at the code to determine at which point the access keys are required.  If you don't have that configured, I'd start there.  Otherwise, it seems like you have the gems installed.

**Comment by sagrahari1** [comment]
I have not saved the access keys anywhere. I am setting the env variables "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY" using export commands.
Let me know if it would help to save it somewhere. Let me know the location as well to save.

**Comment by sagrahari1** [comment]
One more information - when I do debug i get to see below error message
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing

**Comment by sagrahari1** [comment]
Hi zleswomp,
Any pointers. I am totally stuck at this point and can not proceed.
Any help is really appreciated.

**Comment by garethr** [comment]
HI @sagrahari1 

Lets see if we can't find some information about your environment. If you could run the following commands that should help. Here we're checking if the gem has been successfully installed into the right path.

```
/opt/puppetlabs/puppet/bin/gem list | grep aws
/opt/puppet/bin/puppetserver gem list grep aws
```

It would also be useful to know how you are running Puppet. Could you show the command you run to get the above mentioned debug output?

Just to double check another possible issue, could you also run 

```
which puppet
```

It's possible you have two copies installed which would cause the mentioned problem.

**Comment by sagrahari1** [comment]
Result of commands :- 
/opt/puppetlabs/puppet/bin# gem list | grep aws
aws-sdk-core (2.3.0)
************************************************************************
/opt/puppetlabs/bin# puppetserver gem list grep aws
*** LOCAL GEMS ***
*** LOCAL GEMS ***
aws-sdk-core (2.2.37)

**************************************************************
/opt/puppetlabs/bin# puppet resource --debug ec2_instance
Debug: Runtime environment: puppet_version=4.4.1, ruby_version=2.1.8, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_securitygroup::ProviderV2: feature aws is missing
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_securitygroup::ProviderV2: feature aws is missing
**************************************************************************************************
 which puppet
/usr/local/bin/puppet

**Comment by garethr** [comment]
@sagrahari1 ah ha. That looks like it.

You have two copies of Puppet installed on the machine. /opt/puppetlabs/bin/puppet and  /usr/local/bin/puppet.

This likely means you installed the later from gem given the version number. If you remove that one, and ensure /opt/puppetlabs/bin is in your PATH this should work.

Also, try explicitly running the PE version:

```
/opt/puppetlabs/bin/puppet resource --debug ec2_instance
```

**Comment by sagrahari1** [comment]
Thanks Gareth for pointing it out. Will it help to just delete /user/bin/puppet or what is the best way to uninstall from this location

**Comment by garethr** [comment]
@sagrahari1 it really depends how it go there. Check apt-get or yum or your package manager of choice for puppet (rather than puppet-agent). Otherwise use the local gem binary (ie. not one in /opt/puppetlabs...) to uninstall.

**Comment by sagrahari1** [comment]
@Garethr , I had an observation which I would like to share. I installed a fresh PE 2016.1.1 on another ubuntu instance and whereis puppet gives be below result
/# whereis puppet
puppet: /usr/local/bin/puppet /opt/puppetlabs/bin/puppet

I dont have ruby/rubygems program installed till now and no aws module. It seems by default puppet is getting installed at two locations.

**Comment by sagrahari1** [comment]
do I still need to uninstall the one at /usr/local/bin/puppet. And if it is getting installed by default with fresh installation , how can I uninstall only from this location. Please suggest

**Comment by garethr** [comment]
@sagrahari1 you don't need to uninstall the one in /usr/local/bin, just use the one in /opt/puppetlabs directly or ensure that the /opt/puppetlabs paths are always in your PATH first.

Regarding uninstalling the existing puppet, it depends how it got there. If the file came from a system package then you can query using dpkg:

```
dpkg -S /usr/local/bin/puppet
```

**Comment by sagrahari1** [comment]
@garethr , after changing the path variable now " which puppet" returns
/opt/puppetlabs/bin/puppet

but still "/opt/puppetlabs/bin# puppet resource --debug ec2_instance" returns the same error:-
Debug: Runtime environment: puppet_version=4.4.1, ruby_version=2.1.8, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing

**Comment by sagrahari1** [comment]
The issue still exists and I dont seem to get any ideas to resolve it. Any more pointers guys ?

**Comment by garethr** [comment]
Have you tried explicitly running 

```
/opt/puppetlabs/bin/puppet resource --debug ec2_instance
```

Note that this is not the same as you have above in the comment, ie. `/opt/puppetlabs/bin# puppet resource`.

I noticed this above as well in the gem commands. Depending on your path these could be different.

```
/opt/puppetlabs/puppet/bin/gem list | grep aws
/opt/puppet/bin/puppetserver gem list grep aws
```

I see different versions of the gem installed as well in the output from the above, which suggests maybe a previous version and path issue.

If you're still having issues I would suggest trying out a vanilla ubuntu VM locally, or talking to the provider of the base operating system image. This still feels like a path problem from the information above.

**Comment by sagrahari1** [comment]
Hi Gareth,
I already tried with a vanilla ubuntu VM and freshly installed aws module following readme steps.
but the error remains the same.
I am printing the output of commands with new VM for your reference

/opt/puppetlabs/puppet/bin# gem list | grep aws
aws-sdk-core (2.3.1)
************************************************************
/opt/puppetlabs/bin# puppetserver gem list grep aws

*** LOCAL GEMS ***



*** LOCAL GEMS ***

aws-sdk-core (2.3.1)
*************************************************************
/opt/puppetlabs/bin# /opt/puppetlabs/bin/puppet resource --debug ec2_instance
Debug: Runtime environment: puppet_version=4.4.1, ruby_version=2.1.8, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing
Debug: Failed to load library 'aws-sdk-core' for feature 'aws'
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature aws is missing
***********************************************************************************************
/opt/puppetlabs/bin# which puppet
/opt/puppetlabs/bin/puppet
****************************************************************
/opt/puppetlabs/bin# echo $PATH                 /opt/puppetlabs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*********************************************************************

**Comment by sagrahari1** [comment]
Hi Gareth,
I shared all the latest configuration in my ubuntu VM. Let me know if you could point to any issues.

**Comment by zleswomp** [comment]
The above `gem list` was not executed with the full path.  That likely needs to be `/opt/puppetlabs/puppet/bin/gem list` to know that the gem is installed in the correct ruby environment.

**Comment by sagrahari1** [comment]
I tried with a fresh CentOS Vm and the issue is resolved. Earlier was using ubuntu VM. still not sure what was the exact cause of issue but I can manage AWS resource now. Thanks for all the help and suggestions.Appreciate it.
I have one more query, is there way in puppet to manage it through external Java program. For example managing AWS resources through a Java program via puppet.

**Comment by garethr** [comment]
@sagrahari1 Good to know. My suspicion is the Ubuntu VM already had some configuration from somewhere which got in thy. In terms of managing via Java you have two options.

You could simply wrap the running of the Puppet binary in Java. So say using `Runtime.getRuntime().exec`.

Alternatively you could load Puppet under JRuby, and use that as an interface. I'm not aware of much prior-art here I'm afraid. Although you can find some examples in https://github.com/puppetlabs/puppetserver of us doing this from Clojure.

**Comment by pablogmorales** [comment]
Hello, Im having the same issue and installed all the aws-sdk

puppet resource --debug ec2_instance
Debug: Runtime environment: puppet_version=5.3.3, ruby_version=2.4.2, run_mode=user, default_encoding=UTF-8
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Could not find translation files for eirc-account at /etc/puppetlabs/code/environments/production/modules/account/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-accounts at /etc/puppetlabs/code/environments/production/modules/accounts/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-apache at /etc/puppetlabs/code/environments/production/modules/apache/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-archive at /etc/puppetlabs/code/environments/production/modules/archive/locales. Skipping i18n initialization.
Debug: Could not find translation files for rmueller-cron at /etc/puppetlabs/code/environments/production/modules/cron/locales. Skipping i18n initialization.
Debug: Could not find translation files for pcfens-filebeat at /etc/puppetlabs/code/environments/production/modules/filebeat/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-gcc at /etc/puppetlabs/code/environments/production/modules/gcc/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-git at /etc/puppetlabs/code/environments/production/modules/git/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-inifile at /etc/puppetlabs/code/environments/production/modules/inifile/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-make at /etc/puppetlabs/code/environments/production/modules/make/locales. Skipping i18n initialization.
Debug: Could not find translation files for gentoo-portage at /etc/puppetlabs/code/environments/production/modules/portage/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-r10k at /etc/puppetlabs/code/environments/production/modules/r10k/locales. Skipping i18n initialization.
Debug: Could not find translation files for lwf-remote_file at /etc/puppetlabs/code/environments/production/modules/remote_file/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-ruby at /etc/puppetlabs/code/environments/production/modules/ruby/locales. Skipping i18n initialization.
Debug: Could not find translation files for sensu-sensu at /etc/puppetlabs/code/environments/production/modules/sensu/locales. Skipping i18n initialization.
Debug: Could not find translation files for saz-ssh at /etc/puppetlabs/code/environments/production/modules/ssh/locales. Skipping i18n initialization.
Debug: Could not find translation files for saz-sudo at /etc/puppetlabs/code/environments/production/modules/sudo/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-vcsrepo at /etc/puppetlabs/code/environments/production/modules/vcsrepo/locales. Skipping i18n initialization.
Debug: Could not find translation files for zebrastuff at /etc/puppetlabs/code/environments/production/modules/zebrastuff/locales. Skipping i18n initialization.
Debug: Could not find translation files for stahnma-epel at /etc/puppetlabs/code/environments/production/modules/epel/locales. Skipping i18n initialization.
Debug: Could not find translation files for darin-zypprepo at /etc/puppetlabs/code/environments/production/modules/zypprepo/locales. Skipping i18n initialization.
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'retries' for feature 'retries': cannot load such file -- retries
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature retries is missing
Debug: Failed to load library 'retries' for feature 'retries': cannot load such file -- retries
Debug: Puppet::Type::Ec2_instance::ProviderV2: feature retries is missing

Any hints?
 puppetlabs-aws (v2.1.0)
puppetserver version: 5.1.4

Thanks
Regards
