### ISSUE TITLE
How to assign an ec2_instance a DNS record?

### ISSUE THREAD

**Issue by zleswomp** [puppetlabs/puppetlabs-aws#301]
Is there a simple way that I'm overlooking to assign a DNS record to a Puppet provisioned ec2_instance without knowing the IP address?  I have a bunch of instances that I'll create with Puppet, but then I want each of them to have an A record associated with them, but I'd like not to need to hardcode the IP addresses, as I expect them to change frequently.  Any advice here would be appreciated.

**Comment by obenziane2** [comment]
Anyone have a solution for this ? basically assign DNS A records dynamically, I've used the facter variables and it fails:

$::hostname = 'myhostname'
$::ipddress = 'myipaddress'

route53_a_record { '$myhostname.':
  ensure => 'present',
  ttl    => '3000',
  values => ['$ipddress'],
  zone   => 'xxxxxxx.com.',
}

**Comment by zleswomp** [comment]
@obenziane2 I've been exporting a `route53_a_record` from each host and realizing it on a node that provisions the rest of our AWS infrastructure.  It works pretty well, it just means that the node has to check in before the record can be populated.  My hope was that we could provision an instance at the same time the record was created, but I don't think that will be easily achieved.

**Comment by zleswomp** [comment]
This will not work as desired in AWS due to the IP being allocated only after the instance is up.  A simple function call could work for instances that didn't check into puppet, but I no longer need this open.
