### ISSUE TITLE
Error: xxxxxxxxx property is read-only once ec2_instance created.

### ISSUE THREAD

**Issue by pierreact** [puppetlabs/puppetlabs-aws#309]
I'm playing with puppet/aws and have met this issue:

Here my manifest:

ec2_instance { 'api-0001':
  ensure        => present,
  image_id      => 'ami-837dcff0', # you need to select your own AMI
  instance_type => 't2.micro',
  subnet        => 'abcd',
  security_groups   => ['net-2'],
  region        => 'eu-west-1',
  monitoring    => false,
  ebs_optimized => false,
}

ec2_securitygroup { 'net-2':
  ensure      => present,
  region      => 'eu-west-1',
  description => 'net2',
  ingress     => [{
    protocol  => 'tcp',
    port      => 22,
    cidr      => '0.0.0.0/0',
  }
],
}

Running it the first time:
**$ puppet apply --verbose aws.pp 
Warning: Could not retrieve fact fqdn
Notice: Compiled catalog for papa in environment production in 0.03 seconds
Info: Applying configuration version '1463828069'
Info: Checking if security group net-2 exists in region eu-west-1
Info: Checking if instance api-0001 is running in region eu-west-1
Info: Checking if instance api-0001 is stopped in region eu-west-1
Info: Starting instance api-0001 in region eu-west-1
Notice: /Stage[main]/Main/Ec2_instance[api-0001]/ensure: changed absent to running
Notice: Finished catalog run in 26.98 seconds**

Running it the second time (Not modifying the manifest):
**$ puppet apply --verbose aws.pp 
Warning: Could not retrieve fact fqdn
Notice: Compiled catalog for papa in environment production in 0.04 seconds
Info: Applying configuration version '1463828227'
Info: Checking if security group net-2 exists in region eu-west-1
Error: monitoring property is read-only once ec2_instance created.
Error: /Stage[main]/Main/Ec2_instance[api-0001]/monitoring: change from absent to false failed: monitoring property is read-only once ec2_instance created.
Error: ebs_optimized property is read-only once ec2_instance created.
Error: /Stage[main]/Main/Ec2_instance[api-0001]/ebs_optimized: change from absent to false failed: ebs_optimized property is read-only once ec2_instance created.
Notice: Finished catalog run in 0.96 seconds**

I have the same behavior with and without those lines.

  **monitoring    => false,
  ebs_optimized => false,**

puppetlabs-aws (v1.4.0)

Please let me know if you want me to run some tests or provide more information, I'll be more than happy to help.

Thank you for your work.

**Comment by zecharyah** [comment]
up.

I have the same error, did you manage to solve it? I think it's a bug.

**Comment by pierreact** [comment]
No, I did not, I wasn't too impressed by the support associated with this and it doesn't encourage me to use it for important matters.

**Comment by pierreact** [comment]
@zecharyah Updated to puppet 4.6, works perfectly now.
