### ISSUE TITLE
Support for managing IAM roles

### ISSUE THREAD

**Issue by reubenavery** [puppetlabs/puppetlabs-aws#322]
We've got support for managing IAM users, policies, and policy attachments to roles, but the ability to manage IAM roles themselves is still missing.

Has anyone attempted addressing this in the past?  Is it not possible with the current AWS SDK?

**Comment by zleswomp** [comment]
This should be pretty quick to do.  It is possible, but I didn't have a use case when I was working on the IAM types and just skipped over it.  I'm working on ECS at the moment and will also need this functionality.  @reubenavery Did you want to give it a go?  I'm happy to if not.

**Comment by reubenavery** [comment]
I believe this is simple enough to do for me to chase after as a first pull request to this project.  Thank you!

**Comment by reubenavery** [comment]
Hi again, I've begun with something very rudimentary, but am stuck getting myself off the ground and would really appreciate some newbie bootstrapping guidance.

I've got this branch here: https://github.com/bitswarmlabs/puppet-aws/tree/features/iam-roles

But I am stuck at getting a simple rake spec to fire off successfully.  My root AWS account's creds are both available as environment vars AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as well as in ~/.aws/credentials and also ~/.fog but I can't seem to get off the ground with getting these new specs to fire off:



  1) Puppet::Type::Iam_role::ProviderV2 with the minimum params self.prefetch exists
     Failure/Error: response = iam_client.list_roles()

     Aws::IAM::Errors::InvalidClientTokenId:
       The security token included in the request is invalid.
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/request.rb:70:in `send_request'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
     # ./lib/puppet/provider/iam_role/v2.rb:10:in `instances'
     # ./spec/unit/provider/iam_role/v2_spec.rb:29:in `block (5 levels) in <top (required)>'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/unit/provider/iam_role/v2_spec.rb:28:in `block (4 levels) in <top (required)>'

  2) Puppet::Type::Iam_role::ProviderV2 with the minimum params exists? should correctly find existing roles
     Failure/Error: response = iam_client.list_roles()

     Aws::IAM::Errors::InvalidClientTokenId:
       The security token included in the request is invalid.
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/request.rb:70:in `send_request'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.3.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
     # ./lib/puppet/provider/iam_role/v2.rb:10:in `instances'
     # ./spec/unit/provider/iam_role/v2_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ./spec/unit/provider/iam_role/v2_spec.rb:44:in `block (5 levels) in <top (required)>'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/ravery/.rvm/gems/ruby-2.3.1/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/unit/provider/iam_role/v2_spec.rb:43:in `block (4 levels) in <top (required)>'

Finished in 3.57 seconds (files took 5.91 seconds to load)
461 examples, 2 failures

Failed examples:

rspec ./spec/unit/provider/iam_role/v2_spec.rb:27 # Puppet::Type::Iam_role::ProviderV2 with the minimum params self.prefetch exists
rspec ./spec/unit/provider/iam_role/v2_spec.rb:42 # Puppet::Type::Iam_role::ProviderV2 with the minimum params exists? should correctly find existing roles

/Users/ravery/.rvm/rubies/ruby-2.3.1/bin/ruby -I/Users/ravery/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib:/Users/ravery/.rvm/gems/ruby-2.3.1/gems/rspec-support-3.5.0/lib /Users/ravery/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration,types\}/\*\*/\*_spec.rb --color failed
------------------------------------------------------------


This is obviously newbie ignorance holding me up, and if you or anyone could give a few moments of your time and bandwidth to point me in the right direction, i would be extremely grateful.

I hate to ask this of anyone, but I am keen to get strongly rolling on contributing here.  There are many other missing and incomplete implementation points of the AWS API I'm very keen on assisting development with.  

Thank you all!

**Comment by zleswomp** [comment]
@reubenavery Great, happy to review when you get it going.

**Comment by reubenavery** [comment]
Am I doing it right? https://github.com/reubenavery/puppetlabs-aws/pull/1

**Comment by zleswomp** [comment]
Thats looking pretty good @reubenavery.  Maybe some style changes there, but the functionality looks there.  I don't understand acceptance testing on this module, so I can't help validate that.

**Comment by zleswomp** [comment]
This has been completed.
