### ISSUE TITLE
Read-only attributes should not fail, only warn

### ISSUE THREAD

**Issue by reubenavery** [puppetlabs/puppetlabs-aws#339]
Failing a catalog run when a read-only attribute is encountered is too harsh a response, in my opinion.  This ought to only generate a warning, or at the very most an error for the given resource, and really only if there is a delta between the value(s).

**Comment by zleswomp** [comment]
See https://github.com/puppetlabs/puppetlabs-aws/pull/334  I also need to file a MODULES ticket for a workaround since the solution I've proposed seems to conflict with the needs of others.

**Comment by ahenroid** [comment]
@zleswomp This was addressed by #334, correct? Can I close this issue?

**Comment by zleswomp** [comment]
I believe so, yes.
