### ISSUE TITLE
Managing AWS IAM roles/users/groups and their policies

### ISSUE THREAD

**Issue by vjanelle** [puppetlabs/puppetlabs-aws#40]
I've been trying to think of a way to manage the users/groups/roles for instances and service accounts in a more automated fashion.  Obviously some things like Virtual MFA tokens and access keys won't be as automatable, but the contents of the permissions in a group should be..

As for roles, they have a weakness where they can't use groups - so any attempts to use them as a coarse grained authorization control to other AWS resources leads to a lot of copy and pasting.

**Comment by lattwood** [comment]
This is the only use case we have for CloudFormation and would greatly aid in adopting this puppet module locally.

**Comment by danieldreier** [comment]
I would like this as well. Specifically, I'd like to create many fine-grained IAM policies based on logic I already have in puppet, for example to restrict a given host's access to an S3 bucket path based on a puppet fact about that node.

**Comment by zleswomp** [comment]
+1

**Comment by nrvale0** [comment]
:+1: @diranged @siminm

**Comment by zleswomp** [comment]
Is anyone actively working on this?

**Comment by zleswomp** [comment]
A PR has been opened to support this: https://github.com/puppetlabs/puppetlabs-aws/pull/316

**Comment by ahenroid** [comment]
This is quite an old issue, but I believe it was addressed by #316. Can I close?

**Comment by zleswomp** [comment]
Yes, this has been merged in.
