### ISSUE TITLE
Error handling on security_group creation

### ISSUE THREAD

**Issue by rhoml** [puppetlabs/puppetlabs-aws#42]
Hi @garethr we already have our cloud in AWS up and running so I am not provisioning any security group which we provision using piculet.

When I add a security group that already exists into puppetlabs-aws I get errors like:
`Error: The permission 'x.x.x.x/32-1-22-22' has already been authorized on the specified group` 

Is that an expected behaviour or perhaps something that should be improved?.

**Comment by garethr** [comment]
Could you post an example of the manifest you're using? That's not the expected behaviour, what you're doing should work.

**Comment by rhoml** [comment]
It looks like this

 ``
 ec2_securitygroup { 'security-group-name':
    ensure           => present,
    region           => $::ec2_placement_region,
    description      => 'XXXXXXX',
    ingress          => [{
      protocol       => 'tcp',
      port           => 6379,
      security_group => 'other-secgroup'
    },
    {
      protocol       => 'udp',
      from_port      => 0,
      to_port        => 65535,
      security_group => 'other-secgroup'
    },
    {
      protocol       => 'tcp',
      port           => 22,
      cidr           => 'x.x.x.x/32'
    }
    ],
    tags        => {
      tag_name => 'value',
    },
  }
``

**Comment by garethr** [comment]
Ah, so we don't quite support that setup yet, although we should do. And we're not validating the ingress rule structure very well yet either.

The details are in
https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/provider/ec2_securitygroup/v2.rb#L91-L110

Basically you can specify a security group OR a protocol/port/cidr combination at present.

So you could do:

```puppet
 ec2_securitygroup { 'security-group-name':
    ensure           => present,
    region           => $::ec2_placement_region,
    description      => 'XXXXXXX',
    ingress          => [{
      security_group => 'other-secgroup'
    },{
      protocol       => 'tcp',
      port           => 22,
      cidr           => 'x.x.x.x/32'
    }],
    tags        => {
      tag_name => 'value',
    },
  }
```

This is nearly, but not quite, what you're after (it opens up tcp ports other than 6379 to the other security group).

I'll leave this issue open here and we'll improve the flexibility and validation of the ingress rules in an upcoming release. Thanks for the example, the more real world cases we have the better the module will be.

**Comment by rhoml** [comment]
Oh, I see. Well sounds ok to me.

**Comment by ahenroid** [comment]
@rhoml, are you still interested in this enhancement? If not, I'd like to close this issue. But if you do want this, I'll leave it on the books.
