### ISSUE TITLE
I need some resources and can't find them in version 1.4.0

### ISSUE THREAD

**Issue by taibi-ibtissam** [puppetlabs/puppetlabs-aws#445]
Hi Guys,
First of all Thanks for the awesome job on this module !!
I need some resources like S3 and iam_role that are not in version '1.4.0' in the Puppet Forge version of the module. 
-Can I instead use your repository/master branch, is it stable enough?
-When are you planning to publish the latest changes to Puppet Forge?

**Comment by zleswomp** [comment]
Hi @taibi-ibtissam, I can't answer when a new release will be cut, but I can say that the master branch is relatively stable for us.  Newer types might still be getting polish, but such is life.  Feel free to file issues if you run into problems.

**Comment by taibi-ibtissam** [comment]
Thanks for the response
