### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by disconn3ct** [puppetlabs/puppetlabs-aws#446]
The last release was a year ago, and is missing a lot of useful enhancements that have been added since then. Is the module ready for a new release? (Personally, the elb health check is high on my list and it looks like it got checked in 8 months ago.)

**Comment by zleswomp** [comment]
+1

**Comment by vrowley** [comment]
It would be great if someone could quickly go through the new code, vet it, and release it officially.

**Comment by dallinb** [comment]
Release 2.0.0 was released 10th May.  See https://github.com/puppetlabs/puppetlabs-aws/blob/2.0.0/CHANGELOG.md for details.
