### ISSUE TITLE
Additional permission required in example IAM policy

### ISSUE THREAD

**Issue by spoofedpacket** [puppetlabs/puppetlabs-aws#450]
Creating an ec2_instance doesn't seem to work out of the box with the IAM policy in `examples/iam-profile/profile.json`

Applying the Getting started example from the README results in:

`"Error: Could not set 'present' on ensure: You are not authorized to perform this operation."`

I enabled cloudtrail logging on our account to discover which specific action was being denied, it appears to be the **ec2:DescribeAccountAttributes** action. Once I added this to the IAM policy associated with the puppetmaster, I was able to create an ec2_instance successfully. Perhaps this should be added to the example IAM policy?

**Comment by zleswomp** [comment]
Thanks for the fix! Looks like this can be closed.
