### ISSUE TITLE
Support Ruby 1.8.7

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/puppetlabs-aws#49]
Hi @garethr 

Could you support Ruby 1.8.7? EL6 ships with that and most enterprise users are still on that platform.

**Comment by ghoneycutt** [comment]
It appears that 1.9 as the docs suggest does not actually work either, since it needs mustache which requires at least Ruby 2.0.0.

**Comment by garethr** [comment]
Mustache should be needed only for running the acceptance tests. Soon these will be able to manage other systems, including with other Ruby environments. 

However, the AWS SDK doesn't support 1.8.7. The upcoming work on the all-in-one installer will allow some of these users to use a modern Ruby however. We'll definitely keep an eye on this based on demand from users.
