### ISSUE TITLE
Error authenticating when running in PE

### ISSUE THREAD

**Issue by daveseff** [puppetlabs/puppetlabs-aws#90]
Puppet Enterprise :: If I run 'puppet agent --onetime --no-daemonize --verbose' I see that my instances, security groups, etc all work as expected.  When the agent runs on it's own I see the following failures in the PE console : 

**change from absent to present failed: Could not set 'present' on ensure: unable to sign request without credentials set at ....**

I have my aws keys stored in /root/.aws/credentials. Is there any place else I need to put them?

**Comment by cjtoolseram** [comment]
May I know any update on the error?

**Comment by garethr** [comment]
@cjtoolseram sorry for not updating here. It appears the agent can clobber the ENVironment variables, including HOME, which is used to calculate the path for the configuration file referenced above.

The recommended approach to avoiding this is to the use IAM, which avoids the need for the configuration file on disk at all (which is good from the point of view of leaking credentials as well).

I have some work to resolve this completely in https://github.com/puppetlabs/puppetlabs-aws/pull/177 too.

**Comment by garethr** [comment]
This was merged in #246, which adds support for a global configuration file.
