### ISSUE TITLE
Unable to Specify LoadBalancers in Autoscaling group

### ISSUE THREAD

**Issue by brianwhigham** [puppetlabs/puppetlabs-aws#92]
I can't figure out how to make load balancers part of my auto-scaling group definition.  I don't think the feature is in this module.  So, I forked the code and tried to add a few lines, mostly copying the "availability_zones" parameter, like this: https://github.com/puppetlabs/puppetlabs-aws/compare/master...brianwhigham:master

But, I get errors like this:

```
Error: Could not prefetch ec2_autoscalinggroup provider 'v2': undefined method `load_balancers' for #<#<Class:0x00000002d0e100>:0x00000002d0e088>

Info: Starting auto scaling group asg-modernmws-api in region us-east-1
Error: Could not set 'present' on ensure: unexpected value at params[:load_balancers] at 82:/etc/puppet/environments/production/modules/s_modernmws/manifests/infrastructure.pp
Error: Could not set 'present' on ensure: unexpected value at params[:load_balancers] at 82:/etc/puppet/environments/production/modules/s_modernmws/manifests/infrastructure.pp
Wrapped exception:
unexpected value at params[:load_balancers]
Error: /Stage[main]/S_modernmws::Infrastructure/Ec2_autoscalinggroup[asg-modernmws-api]/ensure: change from absent to present failed: Could not set 'present' on ensure: unexpected value at params[:load_balancers] at 82:/etc/puppet/environments/production/modules/s_modernmws/manifests/infrastructure.pp
```

I've searched aws-sdk-core, the api reference, and this module and can't figure out how to do it.  I don't even understand at what point the error is being thrown (i.e. amazon response or  at the module level).  I'd think it's the module.  But, I can't find where I'm doing anything different than availability zones.

Thank you

**Comment by garethr** [comment]
@brianwhigham first off, thanks for taking a look and trying to add this feature. Debugging providers takes a bit of getting used to.

The line `Could not prefetch ec2_autoscalinggroup provider' tells me that a failure is occurring in the calls to `prefetch` and `self.instance`. The rest of that line tells me why, specifically their is no method called load_balancers (which you call here: https://github.com/puppetlabs/puppetlabs-aws/compare/master...brianwhigham:master#diff-fe04e9c83b86717f90d7038583b1be63R36
). If you check the API documentation it appears to be called `load_balancer_names`- see http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/Client.html#describe_auto_scaling_groups-instance_method 

The second issue is similar, in that the create method doesn't take a parameter `load_balancers`. It appears to be `load_balancer_names` according to http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/Client.html#create_auto_scaling_group-instance_method.

Hopefully that helps, and ask any questions here. It would be great to see this in a PR when you get it working too.

It's probably worth noting a few of the pull requests as well around ELB and Autoscaling currently open: https://github.com/puppetlabs/puppetlabs-aws/pulls.

**Comment by ahenroid** [comment]
@brianwhigham, I'm doing some house cleaning. Can I close this issue?
